/*******************************************************************************
*
* Header file generated by RDP on Sep 14 2004 16:12:35 from minicalc.bnf
*
*******************************************************************************/
#ifndef MINICALC_H
#define MINICALC_H

#include "scan.h"

/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Sep 14 2004 16:12:35 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_16 /* " */ = SCAN_P_TOP,RDP_T_17 /* ( */,RDP_T_18 /* (* */,RDP_T_19 /* ) */,RDP_T_20 /* * */,RDP_T_21 /* ** */,RDP_T_22 /* + */,RDP_T_23 /* , */,
RDP_T_24 /* - */,RDP_T_25 /* / */,RDP_T_26 /* ; */,RDP_T_27 /* = */,RDP_T_int,RDP_T_print,
RDP_TT_TOP
};

/* Tree data type */

typedef struct rdp_tree_data_node
{
  SCAN_DATA
  
} rdp_tree_data;

/* Symbol table support */
typedef struct mini_data_node
{
 char* id; integer i; 
} mini_data;
extern void * mini;
extern mini_data * mini_temp;
#define mini_cast(x) ((mini_data *)x)

/* Parser start production */
void program(void);

#endif

/* End of mini.h */
