/*******************************************************************************
*
* Parser generated by RDP on Oct 11 2010 13:08:26 from miniloop.bnf
*
*******************************************************************************/
#include <time.h>
#include "ml_aux.h"
#include "miniloop.h"

char
  *rdp_sourcefilename,          /* current source file name */
  **rdp_sourcefilenames,        /* array of source file names */
  *rdp_outputfilename = "miniloop.mvm";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_sourcefilenumber,                /* Source file counter */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'!'\0" 
"'!='\0" "'\"'\0" "'('\0" "'(*'\0" "')'\0" "'*'\0" "'**'\0" "'+'\0" 
"','\0" "'-'\0" "'/'\0" "';'\0" "'<'\0" "'<='\0" "'='\0" "'=='\0" 
"'>'\0" "'>='\0" "'begin'\0" "'do'\0" "'else'\0" "'end'\0" "'if'\0" "'int'\0" 
"'print'\0" "'then'\0" "'while'\0" ;

mini_data * mini_temp = NULL;
void* mini = NULL;

/* Tree update function for noterminal nodes */
static int rdp_tree_update = 0;

rdp_tree_node_data* rdp_tree_last_child;

rdp_tree_node_data* rdp_add_node(char* id, rdp_tree_node_data* rdp_tree)
{
  if (rdp_tree_update)
  {
     rdp_tree_node_data *node  = (rdp_tree_node_data*) graph_insert_node(sizeof(rdp_tree_node_data), rdp_tree);
     if (id != NULL)
       node->id = id;
     else
       memcpy(node, text_scan_data, sizeof(scan_data));
       return node;
  }
  else
    return NULL;
}

rdp_tree_node_data* rdp_add_child(char* id, rdp_tree_node_data* rdp_tree)
{
  if (rdp_tree_update)
  {
    rdp_tree_last_child = (rdp_tree_node_data*) graph_insert_node(sizeof(rdp_tree_node_data), rdp_tree);
      if (id != NULL)
        rdp_tree_last_child->id = id;
    else
      memcpy(rdp_tree_last_child, text_scan_data, sizeof(scan_data));

    ((rdp_tree_edge_data*) graph_insert_edge_after_final(sizeof(rdp_tree_edge_data), rdp_tree_last_child, rdp_tree))->rdp_edge_kind = 1;
    return rdp_tree_last_child;
  }
  else
    return NULL;
}

rdp_tree_node_data* rdp_add_parent(char* id, rdp_tree_node_data* rdp_tree)
{
  if (rdp_tree_update)
  {
    rdp_tree_node_data *parent = (rdp_tree_node_data*) graph_insert_node_parent(sizeof(rdp_tree_node_data), sizeof(rdp_tree_edge_data), rdp_tree);
    if (id != NULL)
      parent->id = id;
    else
      memcpy(parent, text_scan_data, sizeof(scan_data));

    ((rdp_tree_edge_data*) graph_next_out_edge(parent))->rdp_edge_kind = 1;

    return parent;
  }
  else
    return NULL;
}


/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("!", NULL, RDP_T_33 /* ! */, SCAN_P_IGNORE);
  scan_load_keyword("!=", NULL, RDP_T_3361 /* != */, SCAN_P_IGNORE);
  scan_load_keyword("\"", "\\", RDP_T_34 /* " */, SCAN_P_STRING_ESC);
  scan_load_keyword("(", NULL, RDP_T_40 /* ( */, SCAN_P_IGNORE);
  scan_load_keyword("(*", "*)", RDP_T_4042 /* (* */, SCAN_P_COMMENT_NEST);
  scan_load_keyword(")", NULL, RDP_T_41 /* ) */, SCAN_P_IGNORE);
  scan_load_keyword("*", NULL, RDP_T_42 /* * */, SCAN_P_IGNORE);
  scan_load_keyword("**", NULL, RDP_T_4242 /* ** */, SCAN_P_IGNORE);
  scan_load_keyword("+", NULL, RDP_T_43 /* + */, SCAN_P_IGNORE);
  scan_load_keyword(",", NULL, RDP_T_44 /* , */, SCAN_P_IGNORE);
  scan_load_keyword("-", NULL, RDP_T_45 /* - */, SCAN_P_IGNORE);
  scan_load_keyword("/", NULL, RDP_T_47 /* / */, SCAN_P_IGNORE);
  scan_load_keyword(";", NULL, RDP_T_59 /* ; */, SCAN_P_IGNORE);
  scan_load_keyword("<", NULL, RDP_T_60 /* < */, SCAN_P_IGNORE);
  scan_load_keyword("<=", NULL, RDP_T_6061 /* <= */, SCAN_P_IGNORE);
  scan_load_keyword("=", NULL, RDP_T_61 /* = */, SCAN_P_IGNORE);
  scan_load_keyword("==", NULL, RDP_T_6161 /* == */, SCAN_P_IGNORE);
  scan_load_keyword(">", NULL, RDP_T_62 /* > */, SCAN_P_IGNORE);
  scan_load_keyword(">=", NULL, RDP_T_6261 /* >= */, SCAN_P_IGNORE);
  scan_load_keyword("begin", NULL, RDP_T_begin, SCAN_P_IGNORE);
  scan_load_keyword("do", NULL, RDP_T_do, SCAN_P_IGNORE);
  scan_load_keyword("else", NULL, RDP_T_else, SCAN_P_IGNORE);
  scan_load_keyword("end", NULL, RDP_T_end, SCAN_P_IGNORE);
  scan_load_keyword("if", NULL, RDP_T_if, SCAN_P_IGNORE);
  scan_load_keyword("int", NULL, RDP_T_int, SCAN_P_IGNORE);
  scan_load_keyword("print", NULL, RDP_T_print, SCAN_P_IGNORE);
  scan_load_keyword("then", NULL, RDP_T_then, SCAN_P_IGNORE);
  scan_load_keyword("while", NULL, RDP_T_while, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ String_stop = SET_NULL;
  set_ comment_stop = SET_NULL;
  set_ e0_first = SET_NULL;
  set_ e0_stop = SET_NULL;
  set_ e1_first = SET_NULL;
  set_ e1_stop = SET_NULL;
  set_ e2_first = SET_NULL;
  set_ e2_stop = SET_NULL;
  set_ e3_first = SET_NULL;
  set_ e3_stop = SET_NULL;
  set_ e4_first = SET_NULL;
  set_ e4_stop = SET_NULL;
  set_ e5_first = SET_NULL;
  set_ e5_stop = SET_NULL;
  set_ program_first = SET_NULL;
  set_ program_stop = SET_NULL;
  set_ rdp_e0_6_first = SET_NULL;
  set_ rdp_e0_7_first = SET_NULL;
  set_ rdp_e0_8_first = SET_NULL;
  set_ rdp_e0_9_first = SET_NULL;
  set_ rdp_e1_2_first = SET_NULL;
  set_ rdp_e1_3_first = SET_NULL;
  set_ rdp_e1_4_first = SET_NULL;
  set_ rdp_e1_5_first = SET_NULL;
  set_ rdp_e2_2_first = SET_NULL;
  set_ rdp_e2_3_first = SET_NULL;
  set_ rdp_e2_4_first = SET_NULL;
  set_ rdp_e2_5_first = SET_NULL;
  set_ rdp_e3_2_first = SET_NULL;
  set_ rdp_e3_3_first = SET_NULL;
  set_ rdp_e3_4_first = SET_NULL;
  set_ rdp_e3_5_first = SET_NULL;
  set_ rdp_e4_2_first = SET_NULL;
  set_ rdp_program_1_first = SET_NULL;
  set_ rdp_program_2_first = SET_NULL;
  set_ rdp_program_3_first = SET_NULL;
  set_ rdp_program_4_first = SET_NULL;
  set_ rdp_program_5_first = SET_NULL;
  set_ rdp_statement_10_first = SET_NULL;
  set_ rdp_statement_5_first = SET_NULL;
  set_ rdp_statement_7_first = SET_NULL;
  set_ rdp_statement_9_first = SET_NULL;
  set_ statement_first = SET_NULL;
  set_ statement_stop = SET_NULL;
  set_ var_dec_stop = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&String_stop, SCAN_P_EOF, RDP_T_41 /* ) */, RDP_T_44 /* , */,SET_END);
  set_assign_list(&comment_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&e0_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&e0_stop, SCAN_P_EOF, RDP_T_41 /* ) */, RDP_T_44 /* , */, RDP_T_59 /* ; */, RDP_T_do, RDP_T_else, 
RDP_T_end, RDP_T_then,SET_END);
  set_assign_list(&e1_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&e1_stop, SCAN_P_EOF, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_44 /* , */, RDP_T_59 /* ; */, 
RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_do, RDP_T_else, RDP_T_end, RDP_T_then,SET_END);
  set_assign_list(&e2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&e2_stop, SCAN_P_EOF, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_43 /* + */, RDP_T_44 /* , */, 
RDP_T_45 /* - */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_do, RDP_T_else, RDP_T_end, RDP_T_then,SET_END);
  set_assign_list(&e3_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&e3_stop, SCAN_P_EOF, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_43 /* + */, 
RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_47 /* / */, RDP_T_59 /* ; */, RDP_T_60 /* < */, 
RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, RDP_T_6261 /* >= */, 
RDP_T_do, RDP_T_else, RDP_T_end, RDP_T_then,SET_END);
  set_assign_list(&e4_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&e4_stop, SCAN_P_EOF, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_43 /* + */, 
RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_47 /* / */, RDP_T_59 /* ; */, RDP_T_60 /* < */, 
RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, RDP_T_6261 /* >= */, 
RDP_T_do, RDP_T_else, RDP_T_end, RDP_T_then,SET_END);
  set_assign_list(&e5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&e5_stop, SCAN_P_EOF, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4242 /* ** */, 
RDP_T_43 /* + */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_47 /* / */, RDP_T_59 /* ; */, 
RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_do, RDP_T_else, RDP_T_end, RDP_T_then,SET_END);
  set_assign_list(&program_first, SCAN_P_ID, RDP_T_59 /* ; */, RDP_T_begin, RDP_T_if, RDP_T_int, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&program_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&rdp_e0_6_first, RDP_T_3361 /* != */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, SET_END);
  set_assign_list(&rdp_e0_7_first, RDP_T_3361 /* != */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, SET_END);
  set_assign_list(&rdp_e0_8_first, RDP_T_3361 /* != */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, SET_END);
  set_assign_list(&rdp_e0_9_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e1_2_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e1_3_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e1_4_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e1_5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e2_2_first, RDP_T_42 /* * */, RDP_T_47 /* / */, SET_END);
  set_assign_list(&rdp_e2_3_first, RDP_T_42 /* * */, RDP_T_47 /* / */, SET_END);
  set_assign_list(&rdp_e2_4_first, RDP_T_42 /* * */, RDP_T_47 /* / */, SET_END);
  set_assign_list(&rdp_e2_5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e3_2_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e3_3_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e3_4_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e3_5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e4_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&rdp_program_1_first, SCAN_P_ID, RDP_T_begin, RDP_T_if, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&rdp_program_2_first, SCAN_P_ID, RDP_T_begin, RDP_T_if, RDP_T_int, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&rdp_program_3_first, SCAN_P_ID, RDP_T_59 /* ; */, RDP_T_begin, RDP_T_if, RDP_T_int, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&rdp_program_4_first, SCAN_P_ID, RDP_T_59 /* ; */, RDP_T_begin, RDP_T_if, RDP_T_int, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&rdp_program_5_first, SCAN_P_ID, RDP_T_59 /* ; */, RDP_T_begin, RDP_T_if, RDP_T_int, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&rdp_statement_10_first, SCAN_P_ID, RDP_T_begin, RDP_T_if, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&rdp_statement_5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_statement_7_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_34 /* " */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_statement_9_first, SCAN_P_ID, RDP_T_begin, RDP_T_if, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&statement_first, SCAN_P_ID, RDP_T_begin, RDP_T_if, RDP_T_print, RDP_T_while, SET_END);
  set_assign_list(&statement_stop, SCAN_P_EOF, RDP_T_59 /* ; */, RDP_T_else, RDP_T_end,SET_END);
  set_assign_list(&var_dec_stop, SCAN_P_EOF, RDP_T_59 /* ; */,SET_END);
}

/* Parser forward declarations and macros */
static char* String(rdp_tree_node_data* rdp_tree);
#define check_declared  if (symbol_lookup_key(mini, &dst, NULL) == NULL)\
                      {\
                        text_message(TEXT_ERROR, "Undeclared variable '%s'\n", dst);\
                        symbol_insert_key(mini, &dst, sizeof(char*), sizeof(mini_data));\
                      }\
                   
static char* e0(rdp_tree_node_data* rdp_tree);
static char* e1(rdp_tree_node_data* rdp_tree);
static char* e2(rdp_tree_node_data* rdp_tree);
static char* e3(rdp_tree_node_data* rdp_tree);
static char* e4(rdp_tree_node_data* rdp_tree);
static char* e5(rdp_tree_node_data* rdp_tree);
void program(rdp_tree_node_data* rdp_tree);
static void statement(rdp_tree_node_data* rdp_tree);
static void var_dec(rdp_tree_node_data* rdp_tree);

/* Parser functions */
static char* String(rdp_tree_node_data* rdp_tree)
{
  char* result;
  {
    if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
    scan_test(NULL, RDP_T_34 /* " */, &String_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &String_stop, &String_stop);
   }
  return result;
}

static char* e0(rdp_tree_node_data* rdp_tree)
{
  char* result;
  char* left;
  char* right;
  {
     char* dst; 
    left = e1(rdp_add_child("e1", rdp_tree));
    if (scan_test_set(NULL, &rdp_e0_8_first, NULL))
    { /* Start of rdp_e0_8 */
      while (1)
      {
        {
           dst = new_temporary(); 
          { /* Start of rdp_e0_6 */
            while (1)
            {
              scan_test_set(NULL, &rdp_e0_6_first, &e0_stop);
              {
                if (scan_test(NULL, RDP_T_62 /* > */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_62 /* > */, &e0_stop);
                  scan_();
                  right = e1(rdp_add_child("e1", rdp_tree));
                   emit("GT ", ">", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_60 /* < */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_60 /* < */, &e0_stop);
                  scan_();
                  right = e1(rdp_add_child("e1", rdp_tree));
                   emit("LT ", "<", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_6261 /* >= */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_6261 /* >= */, &e0_stop);
                  scan_();
                  right = e1(rdp_add_child("e1", rdp_tree));
                   emit("GE ", ">=", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_6061 /* <= */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_6061 /* <= */, &e0_stop);
                  scan_();
                  right = e1(rdp_add_child("e1", rdp_tree));
                   emit("LE ", ">=", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_6161 /* == */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_6161 /* == */, &e0_stop);
                  scan_();
                  right = e1(rdp_add_child("e1", rdp_tree));
                   emit("EQ ", "==", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_3361 /* != */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_3361 /* != */, &e0_stop);
                  scan_();
                  right = e1(rdp_add_child("e1", rdp_tree));
                   emit("NE ", "!=", dst, left, right); 
                }
                else
                  scan_test_set(NULL, &rdp_e0_6_first, &e0_stop)                ;
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_e0_6 */
 left = dst; 
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_e0_8 */
    else
    {
      /* default action processing for rdp_e0_8*/
      if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
    }
     result = left; 
    scan_test_set(NULL, &e0_stop, &e0_stop);
   }
  return result;
}

static char* e1(rdp_tree_node_data* rdp_tree)
{
  char* result;
  char* left;
  char* right;
  {
     char* dst; 
    left = e2(rdp_add_child("e2", rdp_tree));
    if (scan_test_set(NULL, &rdp_e1_4_first, NULL))
    { /* Start of rdp_e1_4 */
      while (1)
      {
        {
           dst = new_temporary(); 
          { /* Start of rdp_e1_2 */
            while (1)
            {
              scan_test_set(NULL, &rdp_e1_2_first, &e1_stop);
              {
                if (scan_test(NULL, RDP_T_43 /* + */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_43 /* + */, &e1_stop);
                  scan_();
                  right = e2(rdp_add_child("e2", rdp_tree));
                   emit("ADD", "+", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_45 /* - */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_45 /* - */, &e1_stop);
                  scan_();
                  right = e2(rdp_add_child("e2", rdp_tree));
                   emit("SUB", "-", dst, left, right); 
                }
                else
                  scan_test_set(NULL, &rdp_e1_2_first, &e1_stop)                ;
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_e1_2 */
 left = dst; 
          }
        if (!scan_test_set(NULL, &rdp_e1_4_first, NULL)) break;
      }
    } /* end of rdp_e1_4 */
    else
    {
      /* default action processing for rdp_e1_4*/
      if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
    }
     result = left; 
    scan_test_set(NULL, &e1_stop, &e1_stop);
   }
  return result;
}

static char* e2(rdp_tree_node_data* rdp_tree)
{
  char* result;
  char* left;
  char* right;
  {
     char* dst; 
    left = e3(rdp_add_child("e3", rdp_tree));
    if (scan_test_set(NULL, &rdp_e2_4_first, NULL))
    { /* Start of rdp_e2_4 */
      while (1)
      {
        {
           dst = new_temporary(); 
          { /* Start of rdp_e2_2 */
            while (1)
            {
              scan_test_set(NULL, &rdp_e2_2_first, &e2_stop);
              {
                if (scan_test(NULL, RDP_T_42 /* * */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_42 /* * */, &e2_stop);
                  scan_();
                  right = e3(rdp_add_child("e3", rdp_tree));
                   emit("MUL", "*", dst, left, right); 
                }
                else
                if (scan_test(NULL, RDP_T_47 /* / */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_47 /* / */, &e2_stop);
                  scan_();
                  right = e3(rdp_add_child("e3", rdp_tree));
                   emit("DIV", "/", dst, left, right); 
                }
                else
                  scan_test_set(NULL, &rdp_e2_2_first, &e2_stop)                ;
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_e2_2 */
 left = dst; 
          }
        if (!scan_test_set(NULL, &rdp_e2_4_first, NULL)) break;
      }
    } /* end of rdp_e2_4 */
    else
    {
      /* default action processing for rdp_e2_4*/
      if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
    }
     result = left; 
    scan_test_set(NULL, &e2_stop, &e2_stop);
   }
  return result;
}

static char* e3(rdp_tree_node_data* rdp_tree)
{
  char* result;
  {
     int negate = 0; char* dst;
    if (scan_test_set(NULL, &rdp_e3_4_first, NULL))
    { /* Start of rdp_e3_4 */
      while (1)
      {
        {
          { /* Start of rdp_e3_2 */
            while (1)
            {
              scan_test_set(NULL, &rdp_e3_2_first, &e3_stop);
              {
                if (scan_test(NULL, RDP_T_43 /* + */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_43 /* + */, &e3_stop);
                  scan_();
                }
                else
                if (scan_test(NULL, RDP_T_45 /* - */, NULL))
                {
                  if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                  scan_test(NULL, RDP_T_45 /* - */, &e3_stop);
                  scan_();
                   negate ^= 1; 
                }
                else
                  scan_test_set(NULL, &rdp_e3_2_first, &e3_stop)                ;
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_e3_2 */
          }
        if (!scan_test_set(NULL, &rdp_e3_4_first, NULL)) break;
      }
    } /* end of rdp_e3_4 */
    else
    {
      /* default action processing for rdp_e3_4*/
      if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
    }
    result = e4(rdp_add_child("e4", rdp_tree));
     if (negate) {dst = new_temporary(); emit("SUB", "-", dst, "0", result); result = dst; } 
    scan_test_set(NULL, &e3_stop, &e3_stop);
   }
  return result;
}

static char* e4(rdp_tree_node_data* rdp_tree)
{
  char* result;
  char* left;
  char* right;
  {
     char *dst; 
    left = e5(rdp_add_child("e5", rdp_tree));
    if (scan_test(NULL, RDP_T_4242 /* ** */, NULL))
    { /* Start of rdp_e4_1 */
      while (1)
      {
        {
           dst = new_temporary(); 
          if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
          scan_test(NULL, RDP_T_4242 /* ** */, &e4_stop);
          scan_();
          right = e4(rdp_add_child("e4", rdp_tree));
           emit("EXP", "**", dst, left, right);   left = dst; 
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_e4_1 */
    else
    {
      /* default action processing for rdp_e4_1*/
      if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
    }
     result = left; 
    scan_test_set(NULL, &e4_stop, &e4_stop);
   }
  return result;
}

static char* e5(rdp_tree_node_data* rdp_tree)
{
  char* result;
  char* dst;
  long int val;
  {
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, SCAN_P_ID, &e5_stop);
      dst = SCAN_CAST->id;
      scan_();
      check_declared;
       result = dst; 
    }
    else
    if (scan_test(NULL, SCAN_P_INTEGER, NULL))
    {
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, SCAN_P_INTEGER, &e5_stop);
      val = SCAN_CAST->data.i;
      scan_();
       result = (char*) mem_malloc(12); sprintf(result, "#%lu", val); 
    }
    else
    if (scan_test(NULL, RDP_T_40 /* ( */, NULL))
    {
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_40 /* ( */, &e5_stop);
      scan_();
      result = e1(rdp_add_child("e1", rdp_tree));
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_41 /* ) */, &e5_stop);
      scan_();
    }
    else
      scan_test_set(NULL, &e5_first, &e5_stop)    ;
    scan_test_set(NULL, &e5_stop, &e5_stop);
   }
  return result;
}

void program(rdp_tree_node_data* rdp_tree)
{
  {
     emit_open(rdp_sourcefilename, rdp_outputfilename); 
    if (scan_test_set(NULL, &rdp_program_4_first, NULL))
    { /* Start of rdp_program_4 */
      while (1)
      {
        {
          if (scan_test_set(NULL, &rdp_program_2_first, NULL))
          { /* Start of rdp_program_2 */
            while (1)
            {
              {
                if (scan_test(NULL, RDP_T_int, NULL))
                {
                  var_dec(rdp_add_child("var_dec", rdp_tree));
                }
                else
                if (scan_test_set(NULL, &rdp_program_1_first, NULL))
                {
                  statement(rdp_add_child("statement", rdp_tree));
                }
                else
                  scan_test_set(NULL, &rdp_program_2_first, &program_stop)                ;
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_program_2 */
          else
          {
            /* default action processing for rdp_program_2*/
            if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
          }
          if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
          scan_test(NULL, RDP_T_59 /* ; */, &program_stop);
          scan_();
          }
        if (!scan_test_set(NULL, &rdp_program_4_first, NULL)) break;
      }
    } /* end of rdp_program_4 */
    else
    {
      /* default action processing for rdp_program_4*/
      if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
    }
     emit_close(); 
    scan_test_set(NULL, &program_stop, &program_stop);
   }
}

static void statement(rdp_tree_node_data* rdp_tree)
{
  char* dst;
  char* left;
  {
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, SCAN_P_ID, &statement_stop);
      dst = SCAN_CAST->id;
      scan_();
      check_declared;
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_61 /* = */, &statement_stop);
      scan_();
      left = e0(rdp_add_child("e0", rdp_tree));
       emit("CPY", "", dst, left, NULL); 
    }
    else
    if (scan_test(NULL, RDP_T_if, NULL))
    {
       integer label = new_label();  emitf("__IF_%lu:\n", label); 
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_if, &statement_stop);
      scan_();
      left = e0(rdp_add_child("e0", rdp_tree));
       emitf(" BEQ  %s,__ELSE_%lu\t;ifn %s go to __ELSE_%lu \n",left,label,left, label); 
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_then, &statement_stop);
      scan_();
      statement(rdp_add_child("statement", rdp_tree));
       emitf(" BRA  __FI_%lu\t;go to __FI_%lu\n__ELSE_%lu:\n", label, label, label); 
      if (scan_test(NULL, RDP_T_else, NULL))
      { /* Start of rdp_statement_2 */
      /* WARNING - an LL(1) violation was detected at this point in the grammar */
        while (1)
        {
          {
            if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
            scan_test(NULL, RDP_T_else, &statement_stop);
            scan_();
            statement(rdp_add_child("statement", rdp_tree));
            }
          break;   /* hi limit is 1! */
        }
      } /* end of rdp_statement_2 */
      else
      {
        /* default action processing for rdp_statement_2*/
        if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
      }
       emitf("__FI_%lu:\n", label); 
    }
    else
    if (scan_test(NULL, RDP_T_while, NULL))
    {
       integer label = new_label();  emitf("__DO_%lu:\n", label); 
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_while, &statement_stop);
      scan_();
      left = e0(rdp_add_child("e0", rdp_tree));
       emitf(" BEQ  %s,__OD_%lu\t;ifn %s go to __OD_%lu \n",left,label,left, label); 
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_do, &statement_stop);
      scan_();
      statement(rdp_add_child("statement", rdp_tree));
       emitf(" BRA  __DO_%lu\t;go to __DO_%lu\n__OD_%lu:\n", label, label, label); 
    }
    else
    if (scan_test(NULL, RDP_T_print, NULL))
    {
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_print, &statement_stop);
      scan_();
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_40 /* ( */, &statement_stop);
      scan_();
      { /* Start of rdp_statement_7 */
        while (1)
        {
          scan_test_set(NULL, &rdp_statement_7_first, &statement_stop);
          {
            if (scan_test_set(NULL, &rdp_statement_5_first, NULL))
            {
              left = e0(rdp_add_child("e0", rdp_tree));
               emit_print('I', left); 
            }
            else
            if (scan_test(NULL, RDP_T_34 /* " */, NULL))
            {
              left = String(rdp_add_child("String", rdp_tree));
               emit_print('S', left); 
            }
            else
              scan_test_set(NULL, &rdp_statement_7_first, &statement_stop)            ;
            }
          if (SCAN_CAST->token != RDP_T_44 /* , */) break;
if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                    scan_();
        }
      } /* end of rdp_statement_7 */
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_41 /* ) */, &statement_stop);
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_begin, NULL))
    {
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_begin, &statement_stop);
      scan_();
      { /* Start of rdp_statement_10 */
        while (1)
        {
          scan_test_set(NULL, &rdp_statement_10_first, &statement_stop);
          {
            statement(rdp_add_child("statement", rdp_tree));
            }
          if (SCAN_CAST->token != RDP_T_59 /* ; */) break;
if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                    scan_();
        }
      } /* end of rdp_statement_10 */
      if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
      scan_test(NULL, RDP_T_end, &statement_stop);
      scan_();
    }
    else
      scan_test_set(NULL, &statement_first, &statement_stop)    ;
    scan_test_set(NULL, &statement_stop, &statement_stop);
   }
}

static void var_dec(rdp_tree_node_data* rdp_tree)
{
  char* dst;
  char* left;
  {
    if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
    scan_test(NULL, RDP_T_int, &var_dec_stop);
    scan_();
    { /* Start of rdp_var_dec_3 */
      while (1)
      {
        scan_test(NULL, SCAN_P_ID, &var_dec_stop);
        {
          if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
          scan_test(NULL, SCAN_P_ID, &var_dec_stop);
          dst = SCAN_CAST->id;
          scan_();
           emitf(" \n DATA\n%s: WORD 1\n\n CODE\n",dst); 
          if (scan_test(NULL, RDP_T_61 /* = */, NULL))
          { /* Start of rdp_var_dec_1 */
            while (1)
            {
              {
                if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                scan_test(NULL, RDP_T_61 /* = */, &var_dec_stop);
                scan_();
                left = e0(rdp_add_child("e0", rdp_tree));
                 emit("CPY", "", dst, left, NULL); 
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_var_dec_1 */
          else
          {
            /* default action processing for rdp_var_dec_1*/
            if (rdp_tree_update) {rdp_tree_node_data *temp = rdp_add_child(NULL, rdp_tree); temp->id = NULL; temp->token = SCAN_P_ID;}
          }
           symbol_insert_key(mini, &dst, sizeof(char*), sizeof(mini_data)); \
                       if (*dst == '_' && *(dst+1) == '_')\
                         text_message(TEXT_ERROR_ECHO, "variable names must not begin with two underscores\n");\
                    
          }
        if (SCAN_CAST->token != RDP_T_44 /* , */) break;
if (rdp_tree_update) rdp_add_child(NULL, rdp_tree);
                scan_();
      }
    } /* end of rdp_var_dec_3 */
    scan_test_set(NULL, &var_dec_stop, &var_dec_stop);
   }
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0,            /* make listing flag */

    rdp_lexicalise = 0;            /* print lexicalised output flag */

  unsigned long rdp_textsize = 35000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  rdp_tree_node_data* rdp_tree = (rdp_tree_node_data*) graph_insert_graph("RDP derivation tree");  /* hook for derivation tree */
  rdp_tree_node_data* rdp_tree_root;

  arg_message("Miniloop compiler V1.50 (c) Adrian Johnstone 1997\n" RDP_STAMP "\n\n""Usage: miniloop [options] source[.m]");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_boolean('L', "Print lexicalised source file", &rdp_lexicalise);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);

  rdp_sourcefilenames = arg_process(argc, argv);

  /* Fix up filetypes */
  for (rdp_sourcefilenumber = 0; rdp_sourcefilenames[rdp_sourcefilenumber] != NULL; rdp_sourcefilenumber++)
    rdp_sourcefilenames[rdp_sourcefilenumber] = text_default_filetype(rdp_sourcefilenames[rdp_sourcefilenumber], "m");

  if (rdp_filter)
  {
    rdp_sourcefilenames[0] = "-";
    rdp_outputfilename = "-";
    rdp_sourcefilenames[1] = NULL;     /* make sure no further filenames are taken from the array */

  }
  if ((rdp_sourcefilename = rdp_sourcefilenames[0]) == NULL)
     arg_help("no source files specified");

  if (rdp_sourcefilenames[1] != NULL)
    text_message(TEXT_FATAL, "multiple source files not allowed\n");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 0, 0, rdp_symbol_echo, rdp_tokens);
  if (rdp_lexicalise)
    scan_lexicalise();
  mini = symbol_new_table("mini", 101, 31, symbol_compare_string, symbol_hash_string, symbol_print_string);
  rdp_set_initialise();
  rdp_load_keywords();
  if (rdp_verbose)
     text_printf("\nMiniloop compiler V1.50 (c) Adrian Johnstone 1997\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    rdp_tree_update = rdp_pass == RDP_PASSES;
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));

    for (rdp_sourcefilenumber = 0; (rdp_sourcefilename = rdp_sourcefilenames[rdp_sourcefilenumber]) != NULL; rdp_sourcefilenumber++)
    {
      if (text_open(rdp_sourcefilename) == NULL)
        arg_help("unable to open source file");

      text_get_char();
      scan_();

      program(rdp_tree_root = rdp_add_node("program", rdp_tree));            /* call parser at top level */
      if (text_total_errors() != 0)
        text_message(TEXT_FATAL, "error%s detected in source file ''\n", text_total_errors() == 1 ? "" : "s", rdp_sourcefilename);   /* crash quietly */ 
      graph_epsilon_prune_rdp_tree(rdp_tree_root, sizeof(rdp_tree_edge_data));
    }
  }

  rdp_sourcefilename = rdp_sourcefilenames[0];     /* Reset filename to first file in the list */

  graph_set_root(rdp_tree, rdp_tree_root);
  if (rdp_vcg_filename != NULL)
  {
    FILE *rdp_vcg_file;

    if (*rdp_vcg_filename == '\0')   /* No filename supplied */
      rdp_vcg_filename = "rdparser";
    rdp_vcg_file = fopen((rdp_vcg_filename = text_default_filetype(rdp_vcg_filename, "vcg")), "w");

    if (rdp_vcg_file == NULL)
      text_message(TEXT_FATAL, "unable to open VCG file '%s' for write\n", rdp_vcg_filename);

    if (rdp_verbose)
      text_message(TEXT_INFO, "Dumping derivation tree to VCG file '%s'\n", rdp_vcg_filename);

    text_redirect(rdp_vcg_file);
    graph_vcg(rdp_tree, NULL, scan_vcg_print_node, scan_vcg_print_edge);
    text_redirect(stdout);
    fclose(rdp_vcg_file);
  }

  if (rdp_symbol_statistics)
  {
    symbol_print_all_table_statistics(11);
    symbol_print_all_table();

  }
  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of miniloop.c */
