/*******************************************************************************
*
* Parser generated by RDP on Oct 11 2010 13:47:56 from mvmasm.bnf
*
*******************************************************************************/
#include <time.h>
#include "mvm_aux.h"
#include "math.h"
#include "mvm_def.h"
#include "mvmasm.h"

char
  *rdp_sourcefilename,          /* current source file name */
  **rdp_sourcefilenames,        /* array of source file names */
  *rdp_outputfilename = "mvmasm.out";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_sourcefilenumber,                /* Source file counter */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'!'\0" 
"'!='\0" "'\"'\0" "'#'\0" "'&'\0" "'&&'\0" "'('\0" "')'\0" "'*'\0" 
"'**'\0" "'+'\0" "','\0" "'-'\0" "'/'\0" "':'\0" "';'\0" "'<'\0" 
"'<<'\0" "'<='\0" "'='\0" "'=='\0" "'>'\0" "'>='\0" "'>>'\0" "'ADD'\0" 
"'BEQ'\0" "'BLOCKW'\0" "'BNE'\0" "'BRA'\0" "'CODE'\0" "'CPY'\0" "'DATA'\0" "'DIV'\0" 
"'END'\0" "'EQ'\0" "'EQU'\0" "'EXP'\0" "'FALSE'\0" "'GE'\0" "'GT'\0" "'HALT'\0" 
"'INCLUDE'\0" "'LE'\0" "'LT'\0" "'MUL'\0" "'NE'\0" "'PRTI'\0" "'PRTS'\0" "'RST'\0" 
"'STRING'\0" "'SUB'\0" "'TRUE'\0" "'WORD'\0" "'^'\0" "'|'\0" "'||'\0" "'~'\0" 
;

mvmasm_data * mvmasm_temp = NULL;
void* mvmasm = NULL;

/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("!", NULL, RDP_T_33 /* ! */, SCAN_P_IGNORE);
  scan_load_keyword("!=", NULL, RDP_T_3361 /* != */, SCAN_P_IGNORE);
  scan_load_keyword("\"", "\\", RDP_T_34 /* " */, SCAN_P_STRING_ESC);
  scan_load_keyword("#", NULL, RDP_T_35 /* # */, SCAN_P_IGNORE);
  scan_load_keyword("&", NULL, RDP_T_38 /* & */, SCAN_P_IGNORE);
  scan_load_keyword("&&", NULL, RDP_T_3838 /* && */, SCAN_P_IGNORE);
  scan_load_keyword("(", NULL, RDP_T_40 /* ( */, SCAN_P_IGNORE);
  scan_load_keyword(")", NULL, RDP_T_41 /* ) */, SCAN_P_IGNORE);
  scan_load_keyword("*", NULL, RDP_T_42 /* * */, SCAN_P_IGNORE);
  scan_load_keyword("**", NULL, RDP_T_4242 /* ** */, SCAN_P_IGNORE);
  scan_load_keyword("+", NULL, RDP_T_43 /* + */, SCAN_P_IGNORE);
  scan_load_keyword(",", NULL, RDP_T_44 /* , */, SCAN_P_IGNORE);
  scan_load_keyword("-", NULL, RDP_T_45 /* - */, SCAN_P_IGNORE);
  scan_load_keyword("/", NULL, RDP_T_47 /* / */, SCAN_P_IGNORE);
  scan_load_keyword(":", NULL, RDP_T_58 /* : */, SCAN_P_IGNORE);
  scan_load_keyword(";", NULL, RDP_T_59 /* ; */, SCAN_P_COMMENT_LINE);
  scan_load_keyword("<", NULL, RDP_T_60 /* < */, SCAN_P_IGNORE);
  scan_load_keyword("<<", NULL, RDP_T_6060 /* << */, SCAN_P_IGNORE);
  scan_load_keyword("<=", NULL, RDP_T_6061 /* <= */, SCAN_P_IGNORE);
  scan_load_keyword("=", NULL, RDP_T_61 /* = */, SCAN_P_IGNORE);
  scan_load_keyword("==", NULL, RDP_T_6161 /* == */, SCAN_P_IGNORE);
  scan_load_keyword(">", NULL, RDP_T_62 /* > */, SCAN_P_IGNORE);
  scan_load_keyword(">=", NULL, RDP_T_6261 /* >= */, SCAN_P_IGNORE);
  scan_load_keyword(">>", NULL, RDP_T_6262 /* >> */, SCAN_P_IGNORE);
  scan_load_keyword("ADD", NULL, RDP_T_ADD, SCAN_P_IGNORE);
  scan_load_keyword("BEQ", NULL, RDP_T_BEQ, SCAN_P_IGNORE);
  scan_load_keyword("BLOCKW", NULL, RDP_T_BLOCKW, SCAN_P_IGNORE);
  scan_load_keyword("BNE", NULL, RDP_T_BNE, SCAN_P_IGNORE);
  scan_load_keyword("BRA", NULL, RDP_T_BRA, SCAN_P_IGNORE);
  scan_load_keyword("CODE", NULL, RDP_T_CODE, SCAN_P_IGNORE);
  scan_load_keyword("CPY", NULL, RDP_T_CPY, SCAN_P_IGNORE);
  scan_load_keyword("DATA", NULL, RDP_T_DATA, SCAN_P_IGNORE);
  scan_load_keyword("DIV", NULL, RDP_T_DIV, SCAN_P_IGNORE);
  scan_load_keyword("END", NULL, RDP_T_END, SCAN_P_IGNORE);
  scan_load_keyword("EQ", NULL, RDP_T_EQ, SCAN_P_IGNORE);
  scan_load_keyword("EQU", NULL, RDP_T_EQU, SCAN_P_IGNORE);
  scan_load_keyword("EXP", NULL, RDP_T_EXP, SCAN_P_IGNORE);
  scan_load_keyword("FALSE", NULL, RDP_T_FALSE, SCAN_P_IGNORE);
  scan_load_keyword("GE", NULL, RDP_T_GE, SCAN_P_IGNORE);
  scan_load_keyword("GT", NULL, RDP_T_GT, SCAN_P_IGNORE);
  scan_load_keyword("HALT", NULL, RDP_T_HALT, SCAN_P_IGNORE);
  scan_load_keyword("INCLUDE", NULL, RDP_T_INCLUDE, SCAN_P_IGNORE);
  scan_load_keyword("LE", NULL, RDP_T_LE, SCAN_P_IGNORE);
  scan_load_keyword("LT", NULL, RDP_T_LT, SCAN_P_IGNORE);
  scan_load_keyword("MUL", NULL, RDP_T_MUL, SCAN_P_IGNORE);
  scan_load_keyword("NE", NULL, RDP_T_NE, SCAN_P_IGNORE);
  scan_load_keyword("PRTI", NULL, RDP_T_PRTI, SCAN_P_IGNORE);
  scan_load_keyword("PRTS", NULL, RDP_T_PRTS, SCAN_P_IGNORE);
  scan_load_keyword("RST", NULL, RDP_T_RST, SCAN_P_IGNORE);
  scan_load_keyword("STRING", NULL, RDP_T_STRING, SCAN_P_IGNORE);
  scan_load_keyword("SUB", NULL, RDP_T_SUB, SCAN_P_IGNORE);
  scan_load_keyword("TRUE", NULL, RDP_T_TRUE, SCAN_P_IGNORE);
  scan_load_keyword("WORD", NULL, RDP_T_WORD, SCAN_P_IGNORE);
  scan_load_keyword("^", NULL, RDP_T_94 /* ^ */, SCAN_P_IGNORE);
  scan_load_keyword("|", NULL, RDP_T_124 /* | */, SCAN_P_IGNORE);
  scan_load_keyword("||", NULL, RDP_T_124124 /* || */, SCAN_P_IGNORE);
  scan_load_keyword("~", NULL, RDP_T_126 /* ~ */, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ Comment_stop = SET_NULL;
  set_ branch_first = SET_NULL;
  set_ branch_stop = SET_NULL;
  set_ code_first = SET_NULL;
  set_ code_stop = SET_NULL;
  set_ copy_stop = SET_NULL;
  set_ diadic_first = SET_NULL;
  set_ diadic_stop = SET_NULL;
  set_ directive_first = SET_NULL;
  set_ directive_stop = SET_NULL;
  set_ e0_first = SET_NULL;
  set_ e0_stop = SET_NULL;
  set_ e1_first = SET_NULL;
  set_ e1_stop = SET_NULL;
  set_ e10_first = SET_NULL;
  set_ e10_stop = SET_NULL;
  set_ e11_first = SET_NULL;
  set_ e11_stop = SET_NULL;
  set_ e2_first = SET_NULL;
  set_ e2_stop = SET_NULL;
  set_ e3_first = SET_NULL;
  set_ e3_stop = SET_NULL;
  set_ e4_first = SET_NULL;
  set_ e4_stop = SET_NULL;
  set_ e5_first = SET_NULL;
  set_ e5_stop = SET_NULL;
  set_ e6_first = SET_NULL;
  set_ e6_stop = SET_NULL;
  set_ e7_first = SET_NULL;
  set_ e7_stop = SET_NULL;
  set_ e8_first = SET_NULL;
  set_ e8_stop = SET_NULL;
  set_ e9_first = SET_NULL;
  set_ e9_stop = SET_NULL;
  set_ halt_stop = SET_NULL;
  set_ instr_first = SET_NULL;
  set_ instr_stop = SET_NULL;
  set_ label_stop = SET_NULL;
  set_ print_first = SET_NULL;
  set_ print_stop = SET_NULL;
  set_ rdp_code_2_first = SET_NULL;
  set_ rdp_code_3_first = SET_NULL;
  set_ rdp_code_4_first = SET_NULL;
  set_ rdp_diadic_60_first = SET_NULL;
  set_ rdp_diadic_61_first = SET_NULL;
  set_ rdp_directive_1_first = SET_NULL;
  set_ rdp_directive_2_first = SET_NULL;
  set_ rdp_directive_4_first = SET_NULL;
  set_ rdp_directive_5_first = SET_NULL;
  set_ rdp_e10_4_first = SET_NULL;
  set_ rdp_e11_2_first = SET_NULL;
  set_ rdp_e1_6_first = SET_NULL;
  set_ rdp_e1_7_first = SET_NULL;
  set_ rdp_e2_2_first = SET_NULL;
  set_ rdp_e3_2_first = SET_NULL;
  set_ rdp_e4_2_first = SET_NULL;
  set_ rdp_e5_2_first = SET_NULL;
  set_ rdp_e6_2_first = SET_NULL;
  set_ rdp_e7_2_first = SET_NULL;
  set_ rdp_e7_3_first = SET_NULL;
  set_ rdp_e8_2_first = SET_NULL;
  set_ rdp_e8_3_first = SET_NULL;
  set_ rdp_e9_2_first = SET_NULL;
  set_ rdp_e9_3_first = SET_NULL;
  set_ rdp_instr_0_first = SET_NULL;
  set_ rdp_instr_2_first = SET_NULL;
  set_ rdp_instr_3_first = SET_NULL;
  set_ rdp_instr_5_first = SET_NULL;
  set_ rdp_print_4_first = SET_NULL;
  set_ rdp_print_5_first = SET_NULL;
  set_ rdp_unit_0_first = SET_NULL;
  set_ rdp_unit_1_first = SET_NULL;
  set_ rdp_unit_2_first = SET_NULL;
  set_ string_stop = SET_NULL;
  set_ unit_first = SET_NULL;
  set_ unit_stop = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&Comment_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&branch_first, RDP_T_BEQ, RDP_T_BNE, RDP_T_BRA, SET_END);
  set_assign_list(&branch_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&code_first, SCAN_P_ID, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, 
RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, 
RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, 
RDP_T_WORD, SET_END);
  set_assign_list(&code_stop, SCAN_P_ID, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, 
RDP_T_BRA, RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, 
RDP_T_EQU, RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, 
RDP_T_LT, RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, 
RDP_T_SUB, RDP_T_WORD,SET_END);
  set_assign_list(&copy_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&diadic_first, RDP_T_ADD, RDP_T_DIV, RDP_T_EQ, RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_RST, RDP_T_SUB, SET_END);
  set_assign_list(&diadic_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&directive_first, RDP_T_BLOCKW, RDP_T_CODE, RDP_T_DATA, RDP_T_END, RDP_T_EQU, RDP_T_INCLUDE, RDP_T_STRING, 
RDP_T_WORD, SET_END);
  set_assign_list(&directive_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&e0_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_FALSE, RDP_T_TRUE, SET_END);
  set_assign_list(&e0_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4242 /* ** */, RDP_T_43 /* + */, RDP_T_44 /* , */, 
RDP_T_45 /* - */, RDP_T_47 /* / */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_6061 /* <= */, 
RDP_T_6161 /* == */, RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, 
RDP_T_94 /* ^ */, RDP_T_124 /* | */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e1_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e1_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_44 /* , */,SET_END);
  set_assign_list(&e10_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e10_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_43 /* + */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_47 /* / */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_6061 /* <= */, 
RDP_T_6161 /* == */, RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, 
RDP_T_94 /* ^ */, RDP_T_124 /* | */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e11_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_FALSE, RDP_T_TRUE, SET_END);
  set_assign_list(&e11_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_43 /* + */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_47 /* / */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_6061 /* <= */, 
RDP_T_6161 /* == */, RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, 
RDP_T_94 /* ^ */, RDP_T_124 /* | */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e2_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_44 /* , */, 
RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */,SET_END);
  set_assign_list(&e3_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e3_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_41 /* ) */, RDP_T_44 /* , */, 
RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e4_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e4_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_3838 /* && */, RDP_T_41 /* ) */, 
RDP_T_44 /* , */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e5_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_3838 /* && */, RDP_T_41 /* ) */, 
RDP_T_44 /* , */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_94 /* ^ */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e6_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e6_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_3838 /* && */, RDP_T_41 /* ) */, 
RDP_T_44 /* , */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_94 /* ^ */, RDP_T_124 /* | */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e7_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e7_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_41 /* ) */, RDP_T_44 /* , */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_94 /* ^ */, RDP_T_124 /* | */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e8_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e8_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_41 /* ) */, RDP_T_44 /* , */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_6061 /* <= */, 
RDP_T_6161 /* == */, RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, 
RDP_T_94 /* ^ */, RDP_T_124 /* | */, RDP_T_124124 /* || */,SET_END);
  set_assign_list(&e9_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&e9_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_3361 /* != */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_41 /* ) */, RDP_T_43 /* + */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_60 /* < */, 
RDP_T_6060 /* << */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_94 /* ^ */, RDP_T_124 /* | */, 
RDP_T_124124 /* || */,SET_END);
  set_assign_list(&halt_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&instr_first, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, RDP_T_CODE, RDP_T_CPY, 
RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, RDP_T_EXP, RDP_T_GE, RDP_T_GT, 
RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, 
RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, RDP_T_WORD, SET_END);
  set_assign_list(&instr_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&label_stop, SCAN_P_EOF, RDP_T_58 /* : */,SET_END);
  set_assign_list(&print_first, RDP_T_PRTI, RDP_T_PRTS, SET_END);
  set_assign_list(&print_stop, SCAN_P_EOF, SCAN_P_EOLN,SET_END);
  set_assign_list(&rdp_code_2_first, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, RDP_T_CODE, RDP_T_CPY, 
RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, RDP_T_EXP, RDP_T_GE, RDP_T_GT, 
RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, 
RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, RDP_T_WORD, SET_END);
  set_assign_list(&rdp_code_3_first, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, RDP_T_CODE, RDP_T_CPY, 
RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, RDP_T_EXP, RDP_T_GE, RDP_T_GT, 
RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, 
RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, RDP_T_WORD, SET_END);
  set_assign_list(&rdp_code_4_first, SCAN_P_ID, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, 
RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, 
RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, 
RDP_T_WORD, SET_END);
  set_assign_list(&rdp_diadic_60_first, RDP_T_ADD, RDP_T_DIV, RDP_T_EQ, RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_RST, RDP_T_SUB, SET_END);
  set_assign_list(&rdp_diadic_61_first, RDP_T_ADD, RDP_T_DIV, RDP_T_EQ, RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_RST, RDP_T_SUB, SET_END);
  set_assign_list(&rdp_directive_1_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_directive_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_directive_4_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_directive_5_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e10_4_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_FALSE, RDP_T_TRUE, SET_END);
  set_assign_list(&rdp_e11_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_40 /* ( */, RDP_T_FALSE, RDP_T_TRUE, SET_END);
  set_assign_list(&rdp_e1_6_first, RDP_T_3361 /* != */, RDP_T_60 /* < */, RDP_T_6061 /* <= */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, SET_END);
  set_assign_list(&rdp_e1_7_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e2_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e3_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e4_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e5_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e6_2_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e7_2_first, RDP_T_6060 /* << */, RDP_T_6262 /* >> */, SET_END);
  set_assign_list(&rdp_e7_3_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e8_2_first, RDP_T_43 /* + */, RDP_T_45 /* - */, SET_END);
  set_assign_list(&rdp_e8_3_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_e9_2_first, RDP_T_42 /* * */, RDP_T_47 /* / */, SET_END);
  set_assign_list(&rdp_e9_3_first, SCAN_P_ID, SCAN_P_INTEGER, RDP_T_33 /* ! */, RDP_T_40 /* ( */, RDP_T_43 /* + */, 
RDP_T_45 /* - */, RDP_T_FALSE, RDP_T_TRUE, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_instr_0_first, RDP_T_ADD, RDP_T_DIV, RDP_T_EQ, RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_RST, RDP_T_SUB, SET_END);
  set_assign_list(&rdp_instr_2_first, RDP_T_BEQ, RDP_T_BNE, RDP_T_BRA, SET_END);
  set_assign_list(&rdp_instr_3_first, RDP_T_PRTI, RDP_T_PRTS, SET_END);
  set_assign_list(&rdp_instr_5_first, RDP_T_BLOCKW, RDP_T_CODE, RDP_T_DATA, RDP_T_END, RDP_T_EQU, RDP_T_INCLUDE, RDP_T_STRING, 
RDP_T_WORD, SET_END);
  set_assign_list(&rdp_print_4_first, RDP_T_PRTI, RDP_T_PRTS, SET_END);
  set_assign_list(&rdp_print_5_first, RDP_T_PRTI, RDP_T_PRTS, SET_END);
  set_assign_list(&rdp_unit_0_first, SCAN_P_ID, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, 
RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, 
RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, 
RDP_T_WORD, SET_END);
  set_assign_list(&rdp_unit_1_first, SCAN_P_ID, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, 
RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, 
RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, 
RDP_T_WORD, SET_END);
  set_assign_list(&rdp_unit_2_first, SCAN_P_ID, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, 
RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, 
RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, 
RDP_T_WORD, SET_END);
  set_assign_list(&string_stop, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_41 /* ) */,SET_END);
  set_assign_list(&unit_first, SCAN_P_ID, SCAN_P_EOLN, RDP_T_ADD, RDP_T_BEQ, RDP_T_BLOCKW, RDP_T_BNE, RDP_T_BRA, 
RDP_T_CODE, RDP_T_CPY, RDP_T_DATA, RDP_T_DIV, RDP_T_END, RDP_T_EQ, RDP_T_EQU, 
RDP_T_EXP, RDP_T_GE, RDP_T_GT, RDP_T_HALT, RDP_T_INCLUDE, RDP_T_LE, RDP_T_LT, 
RDP_T_MUL, RDP_T_NE, RDP_T_PRTI, RDP_T_PRTS, RDP_T_RST, RDP_T_STRING, RDP_T_SUB, 
RDP_T_WORD, SET_END);
  set_assign_list(&unit_stop, SCAN_P_EOF,SET_END);
}

/* Parser forward declarations and macros */
static void branch(void);
static void code(void);
static void copy(void);
static void diadic(void);
static void directive(void);
static integer e0(void);
static integer e1(void);
static integer e10(void);
static integer e11(void);
static integer e2(void);
static integer e3(void);
static integer e4(void);
static integer e5(void);
static integer e6(void);
static integer e7(void);
static integer e8(void);
static integer e9(void);
static void halt(void);
static void instr(void);
static void label(void);
static void print(void);
static char* string(void);
void unit(void);

/* Parser functions */
static void branch(void)
{
  integer src;
  integer label;
  {
    if (scan_test(NULL, RDP_T_BEQ, NULL))
    {
      scan_test(NULL, RDP_T_BEQ, &branch_stop);
      scan_();
      src = e1();
      scan_test(NULL, RDP_T_44 /* , */, &branch_stop);
      scan_();
      label = e1();
       emit_op(OP_BEQ, label, src, 0, 1, 1, 2); 
    }
    else
    if (scan_test(NULL, RDP_T_BNE, NULL))
    {
      scan_test(NULL, RDP_T_BNE, &branch_stop);
      scan_();
      src = e1();
      scan_test(NULL, RDP_T_44 /* , */, &branch_stop);
      scan_();
      label = e1();
       emit_op(OP_BNE, label, src, 0, 1, 1, 2); 
    }
    else
    if (scan_test(NULL, RDP_T_BRA, NULL))
    {
      scan_test(NULL, RDP_T_BRA, &branch_stop);
      scan_();
      label = e1();
       emit_op(OP_BEQ, label, 0, 0, 0, 1, 2); /* force immediate mode */ 
    }
    else
      scan_test_set(NULL, &branch_first, &branch_stop)    ;
    scan_test_set(NULL, &branch_stop, &branch_stop);
   }
}

static void code(void)
{
  {
     emit_eoln(); emit_loc(); last_label = NULL; 
    if (scan_test(NULL, SCAN_P_ID, NULL))
    { /* Start of rdp_code_1 */
      while (1)
      {
        {
          label();
          scan_test(NULL, RDP_T_58 /* : */, &code_stop);
          scan_();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_code_1 */
    if (scan_test_set(NULL, &rdp_code_3_first, NULL))
    { /* Start of rdp_code_3 */
      while (1)
      {
        {
          instr();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_code_3 */
     emit_fill(); 
    scan_test(NULL, SCAN_P_EOLN, &code_stop);
    scan_();
    scan_test_set(NULL, &code_stop, &code_stop);
   }
}

static void copy(void)
{
  integer dst;
  integer src;
  {
     int m1 = 1; 
    scan_test(NULL, RDP_T_CPY, &copy_stop);
    scan_();
    dst = e1();
    scan_test(NULL, RDP_T_44 /* , */, &copy_stop);
    scan_();
    if (scan_test(NULL, RDP_T_35 /* # */, NULL))
    { /* Start of rdp_copy_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_35 /* # */, &copy_stop);
          scan_();
           m1=0; 
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_copy_1 */
    src = e1();
     emit_op(OP_CPY, dst, src, 0, m1, 1, 2); 
    scan_test_set(NULL, &copy_stop, &copy_stop);
   }
}

static void diadic(void)
{
  integer dst;
  integer src1;
  integer src2;
  {
     int op, m1 = 1, m2 = 1; 
    { /* Start of rdp_diadic_60 */
      while (1)
      {
        scan_test_set(NULL, &rdp_diadic_60_first, &diadic_stop);
        {
          if (scan_test(NULL, RDP_T_ADD, NULL))
          {
            scan_test(NULL, RDP_T_ADD, &diadic_stop);
            scan_();
             op = OP_ADD; 
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_1 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_1 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_3 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_3 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_SUB, NULL))
          {
            scan_test(NULL, RDP_T_SUB, &diadic_stop);
            scan_();
             op = OP_SUB; 
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_6 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_6 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_8 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_8 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_MUL, NULL))
          {
            scan_test(NULL, RDP_T_MUL, &diadic_stop);
            scan_();
             op = OP_MUL; 
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_11 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_11 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_13 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_13 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_DIV, NULL))
          {
            scan_test(NULL, RDP_T_DIV, &diadic_stop);
            scan_();
             op = OP_DIV; 
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_16 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_16 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_18 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_18 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_EXP, NULL))
          {
            scan_test(NULL, RDP_T_EXP, &diadic_stop);
            scan_();
             op = OP_EXP; 
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_21 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_21 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_23 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_23 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_RST, NULL))
          {
            scan_test(NULL, RDP_T_RST, &diadic_stop);
            scan_();
             op = OP_RST; 
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_26 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_26 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_28 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_28 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_EQ, NULL))
          {
            scan_test(NULL, RDP_T_EQ, &diadic_stop);
            scan_();
             op = OP_EQ;  
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_31 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_31 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_33 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_33 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_NE, NULL))
          {
            scan_test(NULL, RDP_T_NE, &diadic_stop);
            scan_();
             op = OP_NE;  
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_36 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_36 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_38 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_38 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_GT, NULL))
          {
            scan_test(NULL, RDP_T_GT, &diadic_stop);
            scan_();
             op = OP_GT;  
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_41 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_41 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_43 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_43 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_GE, NULL))
          {
            scan_test(NULL, RDP_T_GE, &diadic_stop);
            scan_();
             op = OP_GE;  
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_46 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_46 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_48 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_48 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_LT, NULL))
          {
            scan_test(NULL, RDP_T_LT, &diadic_stop);
            scan_();
             op = OP_LT;  
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_51 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_51 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_53 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_53 */
            src2 = e1();
          }
          else
          if (scan_test(NULL, RDP_T_LE, NULL))
          {
            scan_test(NULL, RDP_T_LE, &diadic_stop);
            scan_();
             op = OP_LE;  
            dst = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_56 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_56 */
            src1 = e1();
            scan_test(NULL, RDP_T_44 /* , */, &diadic_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_diadic_58 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &diadic_stop);
                  scan_();
                   m2=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_diadic_58 */
            src2 = e1();
          }
          else
            scan_test_set(NULL, &rdp_diadic_60_first, &diadic_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_diadic_60 */
     emit_op(op, dst, src1, src2, m1, m2, 3); 
    scan_test_set(NULL, &diadic_stop, &diadic_stop);
   }
}

static void directive(void)
{
  char* filename;
  integer n;
  integer val;
  char* str;
  {
    if (scan_test(NULL, RDP_T_INCLUDE, NULL))
    {
      scan_test(NULL, RDP_T_INCLUDE, &directive_stop);
      scan_();
      scan_test(NULL, RDP_T_40 /* ( */, &directive_stop);
      scan_();
      filename = string();
      scan_test(NULL, RDP_T_41 /* ) */, &directive_stop);
      scan_();
       if (text_open(filename) == NULL)\
                     text_message(TEXT_ERROR_ECHO, "include file '%s' not found\n", filename);\
                  else\
                  {\
                    text_get_char();\
                    scan_();\
                  }\
               
    }
    else
    if (scan_test(NULL, RDP_T_CODE, NULL))
    {
      scan_test(NULL, RDP_T_CODE, &directive_stop);
      scan_();
       location = &code_location; 
      if (scan_test_set(NULL, &rdp_directive_2_first, NULL))
      { /* Start of rdp_directive_2 */
        while (1)
        {
          {
            n = e1();
             *location = n; 
            }
          break;   /* hi limit is 1! */
        }
      } /* end of rdp_directive_2 */
    }
    else
    if (scan_test(NULL, RDP_T_DATA, NULL))
    {
      scan_test(NULL, RDP_T_DATA, &directive_stop);
      scan_();
       location = &data_location; 
      if (scan_test_set(NULL, &rdp_directive_5_first, NULL))
      { /* Start of rdp_directive_5 */
        while (1)
        {
          {
            n = e1();
             *location = n; 
            }
          break;   /* hi limit is 1! */
        }
      } /* end of rdp_directive_5 */
    }
    else
    if (scan_test(NULL, RDP_T_WORD, NULL))
    {
      scan_test(NULL, RDP_T_WORD, &directive_stop);
      scan_();
      val = e1();
       emit2(val); 
    }
    else
    if (scan_test(NULL, RDP_T_BLOCKW, NULL))
    {
      scan_test(NULL, RDP_T_BLOCKW, &directive_stop);
      scan_();
      val = e1();
       *location += 2 * val; 
    }
    else
    if (scan_test(NULL, RDP_T_STRING, NULL))
    {
      scan_test(NULL, RDP_T_STRING, &directive_stop);
      scan_();
      str = string();
       while (*str!=0) emit1(*str++); emit1(0); 
    }
    else
    if (scan_test(NULL, RDP_T_EQU, NULL))
    {
      scan_test(NULL, RDP_T_EQU, &directive_stop);
      scan_();
      val = e1();
       mvmasm_cast(current_label())->val = val; 
    }
    else
    if (scan_test(NULL, RDP_T_END, NULL))
    {
      scan_test(NULL, RDP_T_END, &directive_stop);
      scan_();
      val = e1();
       transfer = val; emit_transfer(); 
    }
    else
      scan_test_set(NULL, &directive_first, &directive_stop)    ;
    scan_test_set(NULL, &directive_stop, &directive_stop);
   }
}

static integer e0(void)
{
  integer result;
  char* name;
  {
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
       mvmasm_data* temp; 
      scan_test(NULL, SCAN_P_ID, &e0_stop);
      name = SCAN_CAST->id;
      scan_();
       temp = mvmasm_cast(symbol_lookup_key(mvmasm, &name, NULL));\
                  if (temp == NULL)\
                  {\
                    if (rdp_pass == 3)\
                      text_message(TEXT_ERROR_ECHO,"Undefined symbol '%s'\n", name);\
                    result = 0;\
                  }\
                  else\
                    result = temp->val;\
               
    }
    else
    if (scan_test(NULL, SCAN_P_INTEGER, NULL))
    {
      scan_test(NULL, SCAN_P_INTEGER, &e0_stop);
      result = SCAN_CAST->data.i;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_TRUE, NULL))
    {
      scan_test(NULL, RDP_T_TRUE, &e0_stop);
      scan_();
       result = 1; 
    }
    else
    if (scan_test(NULL, RDP_T_FALSE, NULL))
    {
      scan_test(NULL, RDP_T_FALSE, &e0_stop);
      scan_();
       result = 0; 
    }
    else
    if (scan_test(NULL, RDP_T_40 /* ( */, NULL))
    {
      scan_test(NULL, RDP_T_40 /* ( */, &e0_stop);
      scan_();
      result = e2();
      scan_test(NULL, RDP_T_41 /* ) */, &e0_stop);
      scan_();
    }
    else
      scan_test_set(NULL, &e0_first, &e0_stop)    ;
    scan_test_set(NULL, &e0_stop, &e0_stop);
   }
  return result;
}

static integer e1(void)
{
  integer result;
  integer right;
  {
    result = e2();
    if (scan_test_set(NULL, &rdp_e1_6_first, NULL))
    { /* Start of rdp_e1_6 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_62 /* > */, NULL))
          {
            scan_test(NULL, RDP_T_62 /* > */, &e1_stop);
            scan_();
            right = e2();
             result = result > right;  
          }
          else
          if (scan_test(NULL, RDP_T_60 /* < */, NULL))
          {
            scan_test(NULL, RDP_T_60 /* < */, &e1_stop);
            scan_();
            right = e2();
             result = result < right;  
          }
          else
          if (scan_test(NULL, RDP_T_6261 /* >= */, NULL))
          {
            scan_test(NULL, RDP_T_6261 /* >= */, &e1_stop);
            scan_();
            right = e2();
             result = result >= right; 
          }
          else
          if (scan_test(NULL, RDP_T_6061 /* <= */, NULL))
          {
            scan_test(NULL, RDP_T_6061 /* <= */, &e1_stop);
            scan_();
            right = e2();
             result = result <= right; 
          }
          else
          if (scan_test(NULL, RDP_T_6161 /* == */, NULL))
          {
            scan_test(NULL, RDP_T_6161 /* == */, &e1_stop);
            scan_();
            right = e2();
             result = result == right; 
          }
          else
          if (scan_test(NULL, RDP_T_3361 /* != */, NULL))
          {
            scan_test(NULL, RDP_T_3361 /* != */, &e1_stop);
            scan_();
            right = e2();
             result = result != right; 
          }
          else
            scan_test_set(NULL, &rdp_e1_6_first, &e1_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_e1_6 */
    scan_test_set(NULL, &e1_stop, &e1_stop);
   }
  return result;
}

static integer e10(void)
{
  integer result;
  {
    if (scan_test(NULL, RDP_T_43 /* + */, NULL))
    {
      scan_test(NULL, RDP_T_43 /* + */, &e10_stop);
      scan_();
      result = e10();
    }
    else
    if (scan_test(NULL, RDP_T_45 /* - */, NULL))
    {
      scan_test(NULL, RDP_T_45 /* - */, &e10_stop);
      scan_();
      result = e10();
       result = -result; 
    }
    else
    if (scan_test(NULL, RDP_T_126 /* ~ */, NULL))
    {
      scan_test(NULL, RDP_T_126 /* ~ */, &e10_stop);
      scan_();
      result = e10();
       result = ~result; 
    }
    else
    if (scan_test(NULL, RDP_T_33 /* ! */, NULL))
    {
      scan_test(NULL, RDP_T_33 /* ! */, &e10_stop);
      scan_();
      result = e10();
       result = !result; 
    }
    else
    if (scan_test_set(NULL, &rdp_e10_4_first, NULL))
    {
      result = e11();
    }
    else
      scan_test_set(NULL, &e10_first, &e10_stop)    ;
    scan_test_set(NULL, &e10_stop, &e10_stop);
   }
  return result;
}

static integer e11(void)
{
  integer result;
  integer right;
  {
    result = e0();
    if (scan_test(NULL, RDP_T_4242 /* ** */, NULL))
    { /* Start of rdp_e11_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_4242 /* ** */, &e11_stop);
          scan_();
          right = e10();
           result = (integer) pow((double) result, (double) right); 
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_e11_1 */
    scan_test_set(NULL, &e11_stop, &e11_stop);
   }
  return result;
}

static integer e2(void)
{
  integer result;
  integer right;
  {
    result = e3();
    if (scan_test(NULL, RDP_T_124124 /* || */, NULL))
    { /* Start of rdp_e2_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_124124 /* || */, &e2_stop);
          scan_();
          right = e3();
           result = result || right; 
          }
        if (!scan_test(NULL, RDP_T_124124 /* || */, NULL)) break;
      }
    } /* end of rdp_e2_1 */
    scan_test_set(NULL, &e2_stop, &e2_stop);
   }
  return result;
}

static integer e3(void)
{
  integer result;
  integer right;
  {
    result = e4();
    if (scan_test(NULL, RDP_T_3838 /* && */, NULL))
    { /* Start of rdp_e3_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_3838 /* && */, &e3_stop);
          scan_();
          right = e4();
           result = result && right; 
          }
        if (!scan_test(NULL, RDP_T_3838 /* && */, NULL)) break;
      }
    } /* end of rdp_e3_1 */
    scan_test_set(NULL, &e3_stop, &e3_stop);
   }
  return result;
}

static integer e4(void)
{
  integer result;
  integer right;
  {
    result = e5();
    if (scan_test(NULL, RDP_T_94 /* ^ */, NULL))
    { /* Start of rdp_e4_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_94 /* ^ */, &e4_stop);
          scan_();
          right = e5();
           result ^= right; 
          }
        if (!scan_test(NULL, RDP_T_94 /* ^ */, NULL)) break;
      }
    } /* end of rdp_e4_1 */
    scan_test_set(NULL, &e4_stop, &e4_stop);
   }
  return result;
}

static integer e5(void)
{
  integer result;
  integer right;
  {
    result = e6();
    if (scan_test(NULL, RDP_T_124 /* | */, NULL))
    { /* Start of rdp_e5_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_124 /* | */, &e5_stop);
          scan_();
          right = e6();
           result |= right; 
          }
        if (!scan_test(NULL, RDP_T_124 /* | */, NULL)) break;
      }
    } /* end of rdp_e5_1 */
    scan_test_set(NULL, &e5_stop, &e5_stop);
   }
  return result;
}

static integer e6(void)
{
  integer result;
  integer right;
  {
    result = e7();
    if (scan_test(NULL, RDP_T_38 /* & */, NULL))
    { /* Start of rdp_e6_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_38 /* & */, &e6_stop);
          scan_();
          right = e7();
           result &= right; 
          }
        if (!scan_test(NULL, RDP_T_38 /* & */, NULL)) break;
      }
    } /* end of rdp_e6_1 */
    scan_test_set(NULL, &e6_stop, &e6_stop);
   }
  return result;
}

static integer e7(void)
{
  integer result;
  integer right;
  {
    result = e8();
    if (scan_test_set(NULL, &rdp_e7_2_first, NULL))
    { /* Start of rdp_e7_2 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_6060 /* << */, NULL))
          {
            scan_test(NULL, RDP_T_6060 /* << */, &e7_stop);
            scan_();
            right = e8();
             result <<= right; 
          }
          else
          if (scan_test(NULL, RDP_T_6262 /* >> */, NULL))
          {
            scan_test(NULL, RDP_T_6262 /* >> */, &e7_stop);
            scan_();
            right = e8();
             result >>= right; 
          }
          else
            scan_test_set(NULL, &rdp_e7_2_first, &e7_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_e7_2_first, NULL)) break;
      }
    } /* end of rdp_e7_2 */
    scan_test_set(NULL, &e7_stop, &e7_stop);
   }
  return result;
}

static integer e8(void)
{
  integer result;
  integer right;
  {
    result = e9();
    if (scan_test_set(NULL, &rdp_e8_2_first, NULL))
    { /* Start of rdp_e8_2 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_43 /* + */, NULL))
          {
            scan_test(NULL, RDP_T_43 /* + */, &e8_stop);
            scan_();
            right = e9();
             result += right; 
          }
          else
          if (scan_test(NULL, RDP_T_45 /* - */, NULL))
          {
            scan_test(NULL, RDP_T_45 /* - */, &e8_stop);
            scan_();
            right = e9();
             result -= right; 
          }
          else
            scan_test_set(NULL, &rdp_e8_2_first, &e8_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_e8_2_first, NULL)) break;
      }
    } /* end of rdp_e8_2 */
    scan_test_set(NULL, &e8_stop, &e8_stop);
   }
  return result;
}

static integer e9(void)
{
  integer result;
  integer right;
  {
    result = e10();
    if (scan_test_set(NULL, &rdp_e9_2_first, NULL))
    { /* Start of rdp_e9_2 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_42 /* * */, NULL))
          {
            scan_test(NULL, RDP_T_42 /* * */, &e9_stop);
            scan_();
            right = e10();
             result *= right; 
          }
          else
          if (scan_test(NULL, RDP_T_47 /* / */, NULL))
          {
            scan_test(NULL, RDP_T_47 /* / */, &e9_stop);
            scan_();
            right = e10();
             result /= right; 
          }
          else
            scan_test_set(NULL, &rdp_e9_2_first, &e9_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_e9_2_first, NULL)) break;
      }
    } /* end of rdp_e9_2 */
    scan_test_set(NULL, &e9_stop, &e9_stop);
   }
  return result;
}

static void halt(void)
{
  {
    scan_test(NULL, RDP_T_HALT, &halt_stop);
    scan_();
     emit_op(OP_HALT, 0, 0, 0, 1, 1, 0); 
    scan_test_set(NULL, &halt_stop, &halt_stop);
   }
}

static void instr(void)
{
  {
    if (scan_test_set(NULL, &rdp_instr_0_first, NULL))
    {
      diadic();
    }
    else
    if (scan_test(NULL, RDP_T_CPY, NULL))
    {
      copy();
    }
    else
    if (scan_test_set(NULL, &rdp_instr_2_first, NULL))
    {
      branch();
    }
    else
    if (scan_test_set(NULL, &rdp_instr_3_first, NULL))
    {
      print();
    }
    else
    if (scan_test(NULL, RDP_T_HALT, NULL))
    {
      halt();
    }
    else
    if (scan_test_set(NULL, &rdp_instr_5_first, NULL))
    {
      directive();
    }
    else
      scan_test_set(NULL, &instr_first, &instr_stop)    ;
    scan_test_set(NULL, &instr_stop, &instr_stop);
   }
}

static void label(void)
{
  char* lab;
  {
    scan_test(NULL, SCAN_P_ID, &label_stop);
    lab = SCAN_CAST->id;
    scan_();
     if ((last_label = symbol_lookup_key(mvmasm, &lab, NULL)) == NULL)\
               last_label = symbol_insert_key(mvmasm, &lab, sizeof(char*), sizeof(mvmasm_data));\
             mvmasm_cast(last_label)->val = *location;\
          
    scan_test_set(NULL, &label_stop, &label_stop);
   }
}

static void print(void)
{
  integer src;
  {
     int m1 = 1; 
    { /* Start of rdp_print_4 */
      while (1)
      {
        scan_test_set(NULL, &rdp_print_4_first, &print_stop);
        {
          if (scan_test(NULL, RDP_T_PRTS, NULL))
          {
            scan_test(NULL, RDP_T_PRTS, &print_stop);
            scan_();
            src = e1();
             emit_op(OP_PRTS, 0, src, 0, 0, 1, 2); /* force immediate mode */ 
          }
          else
          if (scan_test(NULL, RDP_T_PRTI, NULL))
          {
            scan_test(NULL, RDP_T_PRTI, &print_stop);
            scan_();
            if (scan_test(NULL, RDP_T_35 /* # */, NULL))
            { /* Start of rdp_print_2 */
              while (1)
              {
                {
                  scan_test(NULL, RDP_T_35 /* # */, &print_stop);
                  scan_();
                   m1=0; 
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_print_2 */
            src = e1();
             emit_op(OP_PRTI, 0, src, 0, m1, 1, 2); 
          }
          else
            scan_test_set(NULL, &rdp_print_4_first, &print_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_print_4 */
    scan_test_set(NULL, &print_stop, &print_stop);
   }
}

static char* string(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_34 /* " */, &string_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &string_stop, &string_stop);
   }
  return result;
}

void unit(void)
{
  {
     emit_code = (rdp_pass == 3);\
               data_location = code_location = 0;  /* clear location counters */\
               location = &code_location;          /* make code counter current */\
               dummy_label = symbol_new_symbol(sizeof(mvmasm_data));             /* initialise error symbol */\
            
    if (scan_test_set(NULL, &rdp_unit_1_first, NULL))
    { /* Start of rdp_unit_1 */
      while (1)
      {
        {
          code();
          }
        if (!scan_test_set(NULL, &rdp_unit_1_first, NULL)) break;
      }
    } /* end of rdp_unit_1 */
    scan_test_set(NULL, &unit_stop, &unit_stop);
   }
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0,            /* make listing flag */

    rdp_lexicalise = 0;            /* print lexicalised output flag */

  unsigned long rdp_textsize = 35000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  arg_message("mvmasm v1.5 - absolute assembler for mvm\n" RDP_STAMP "\n\n""Usage: mvmasm [options] source[.mvm]");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_boolean('L', "Print lexicalised source file", &rdp_lexicalise);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);
  arg_boolean('x', "execute assembled code using mvmsim simulator", &execute_sim);
  arg_message("");
  arg_message("You can contact the author (Adrian Johnstone) at:");
  arg_message("");
  arg_message("Computer Science Department, Royal Holloway, University of London");
  arg_message("Egham, Surrey, TW20 0EX UK. Email: A.Johnstone@rhbnc.ac.uk");

  rdp_sourcefilenames = arg_process(argc, argv);

  /* Fix up filetypes */
  for (rdp_sourcefilenumber = 0; rdp_sourcefilenames[rdp_sourcefilenumber] != NULL; rdp_sourcefilenumber++)
    rdp_sourcefilenames[rdp_sourcefilenumber] = text_default_filetype(rdp_sourcefilenames[rdp_sourcefilenumber], "mvm");

  if (rdp_filter)
  {
    rdp_sourcefilenames[0] = "-";
    rdp_outputfilename = "-";
    rdp_sourcefilenames[1] = NULL;     /* make sure no further filenames are taken from the array */

  }
  if ((rdp_sourcefilename = rdp_sourcefilenames[0]) == NULL)
     arg_help("no source files specified");

  if (rdp_sourcefilenames[1] != NULL)
    text_message(TEXT_FATAL, "multiple source files not allowed\n");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 1, 0, rdp_symbol_echo, rdp_tokens);
  if (rdp_lexicalise)
    scan_lexicalise();
  mvmasm = symbol_new_table("mvmasm", 101, 31, symbol_compare_string, symbol_hash_string, symbol_print_string);
  rdp_set_initialise();
  rdp_load_keywords();
   init(rdp_outputfilename); 
  if (rdp_verbose)
     text_printf("\nmvmasm v1.5 - absolute assembler for mvm\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));

    for (rdp_sourcefilenumber = 0; (rdp_sourcefilename = rdp_sourcefilenames[rdp_sourcefilenumber]) != NULL; rdp_sourcefilenumber++)
    {
      if (text_open(rdp_sourcefilename) == NULL)
        arg_help("unable to open source file");

      text_get_char();
      scan_();

      unit();            /* call parser at top level */
      if (text_total_errors() != 0)
        text_message(TEXT_FATAL, "error%s detected in source file ''\n", text_total_errors() == 1 ? "" : "s", rdp_sourcefilename);   /* crash quietly */ 
    }
  }

  rdp_sourcefilename = rdp_sourcefilenames[0];     /* Reset filename to first file in the list */

   quit(rdp_outputfilename); 
  if (rdp_symbol_statistics)
  {
    symbol_print_all_table_statistics(11);
    symbol_print_all_table();

  }
  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of mvmasm.c */
