/*******************************************************************************
*
* Header file generated by RDP on Oct 11 2010 13:47:56 from mvmasm.bnf
*
*******************************************************************************/
#ifndef MVMASM_H
#define MVMASM_H

#include "arg.h"
#include "graph.h"
#include "hist.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"


/* Maximum number of passes */
#define RDP_PASSES 3

/* Time and date stamp */
#define RDP_STAMP "Generated on Oct 11 2010 13:47:56 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_33 /* ! */ = SCAN_P_TOP,RDP_T_3361 /* != */,RDP_T_34 /* " */,RDP_T_35 /* # */,RDP_T_38 /* & */,RDP_T_3838 /* && */,RDP_T_40 /* ( */,RDP_T_41 /* ) */,
RDP_T_42 /* * */,RDP_T_4242 /* ** */,RDP_T_43 /* + */,RDP_T_44 /* , */,RDP_T_45 /* - */,RDP_T_47 /* / */,RDP_T_58 /* : */,RDP_T_59 /* ; */,
RDP_T_60 /* < */,RDP_T_6060 /* << */,RDP_T_6061 /* <= */,RDP_T_61 /* = */,RDP_T_6161 /* == */,RDP_T_62 /* > */,RDP_T_6261 /* >= */,RDP_T_6262 /* >> */,
RDP_T_ADD,RDP_T_BEQ,RDP_T_BLOCKW,RDP_T_BNE,RDP_T_BRA,RDP_T_CODE,RDP_T_CPY,RDP_T_DATA,
RDP_T_DIV,RDP_T_END,RDP_T_EQ,RDP_T_EQU,RDP_T_EXP,RDP_T_FALSE,RDP_T_GE,RDP_T_GT,
RDP_T_HALT,RDP_T_INCLUDE,RDP_T_LE,RDP_T_LT,RDP_T_MUL,RDP_T_NE,RDP_T_PRTI,RDP_T_PRTS,
RDP_T_RST,RDP_T_STRING,RDP_T_SUB,RDP_T_TRUE,RDP_T_WORD,RDP_T_94 /* ^ */,RDP_T_124 /* | */,RDP_T_124124 /* || */,
RDP_T_126 /* ~ */,
RDP_TT_TOP
};

/* Tree data types */

typedef struct rdp_tree_node_data_struct
{
  SCAN_DATA
  
} rdp_tree_node_data;
typedef struct rdp_tree_edge_data_struct
{
  int rdp_edge_kind;
  
} rdp_tree_edge_data;

/* Symbol table support */
typedef struct mvmasm_data_node
{
 char *id;
                     integer val;
             
} mvmasm_data;
extern void * mvmasm;
extern mvmasm_data * mvmasm_temp;
#define mvmasm_cast(x) ((mvmasm_data *)x)

/* Parser start production */
void unit(void);



#endif

/* End of mvmasm.h */
