/*******************************************************************************
*
* Header file generated by RDP on Oct 11 2010 13:08:27 from pascal.bnf
*
*******************************************************************************/
#ifndef PASCAL_H
#define PASCAL_H

#include "arg.h"
#include "graph.h"
#include "hist.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"


/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Oct 11 2010 13:08:27 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_39 /* ' */ = SCAN_P_TOP,RDP_T_40 /* ( */,RDP_T_4042 /* (* */,RDP_T_41 /* ) */,RDP_T_42 /* * */,RDP_T_43 /* + */,RDP_T_44 /* , */,RDP_T_45 /* - */,
RDP_T_46 /* . */,RDP_T_4646 /* .. */,RDP_T_47 /* / */,RDP_T_58 /* : */,RDP_T_5861 /* := */,RDP_T_59 /* ; */,RDP_T_60 /* < */,RDP_T_6061 /* <= */,
RDP_T_6062 /* <> */,RDP_T_61 /* = */,RDP_T_62 /* > */,RDP_T_6261 /* >= */,RDP_T_91 /* [ */,RDP_T_93 /* ] */,RDP_T_94 /* ^ */,RDP_T_and,
RDP_T_array,RDP_T_begin,RDP_T_case,RDP_T_const,RDP_T_default,RDP_T_div,RDP_T_do,RDP_T_downto,
RDP_T_else,RDP_T_end,RDP_T_file,RDP_T_for,RDP_T_forward,RDP_T_function,RDP_T_goto,RDP_T_if,
RDP_T_in,RDP_T_label,RDP_T_mod,RDP_T_nil,RDP_T_not,RDP_T_of,RDP_T_or,RDP_T_packed,
RDP_T_procedure,RDP_T_program,RDP_T_record,RDP_T_repeat,RDP_T_set,RDP_T_then,RDP_T_to,RDP_T_type,
RDP_T_until,RDP_T_var,RDP_T_while,RDP_T_with,RDP_T_123 /* { */,
RDP_TT_TOP
};

/* Tree data types */

typedef struct rdp_tree_node_data_struct
{
  SCAN_DATA
  
} rdp_tree_node_data;
typedef struct rdp_tree_edge_data_struct
{
  int rdp_edge_kind;
  
} rdp_tree_edge_data;

/* Symbol table support */
/* Parser start production */
void prog(rdp_tree_node_data* rdp_tree);



#endif

/* End of pascal.h */
