/*******************************************************************************
*
* Parser generated by RDP on Oct 11 2010 13:08:27 from pretty_c.bnf
*
*******************************************************************************/
#include <time.h>
#include "pr_c_aux.h"
#include "pretty_c.h"

char
  *rdp_sourcefilename,          /* current source file name */
  **rdp_sourcefilenames,        /* array of source file names */
  *rdp_outputfilename = "pretty.c";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_sourcefilenumber,                /* Source file counter */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'!'\0" 
"'!='\0" "'\"'\0" "'#'\0" "'%'\0" "'%='\0" "'&'\0" "'&&'\0" "'&='\0" 
"'\''\0" "'('\0" "')'\0" "'*'\0" "'*='\0" "'+'\0" "'++'\0" "'+='\0" 
"','\0" "'-'\0" "'--'\0" "'-='\0" "'->'\0" "'.'\0" "'..'\0" "'...'\0" 
"'/'\0" "'/*'\0" "'/='\0" "':'\0" "';'\0" "'<'\0" "'<<'\0" "'<<='\0" 
"'<='\0" "'='\0" "'=='\0" "'>'\0" "'>='\0" "'>>'\0" "'>>='\0" "'?'\0" 
"'['\0" "'\\'\0" "']'\0" "'^'\0" "'^='\0" "'auto'\0" "'break'\0" "'case'\0" 
"'char'\0" "'const'\0" "'continue'\0" "'default'\0" "'do'\0" "'double'\0" "'else'\0" "'enum'\0" 
"'extern'\0" "'float'\0" "'for'\0" "'goto'\0" "'if'\0" "'int'\0" "'long'\0" "'register'\0" 
"'return'\0" "'short'\0" "'signed'\0" "'sizeof'\0" "'static'\0" "'struct'\0" "'switch'\0" "'typedef'\0" 
"'union'\0" "'unsigned'\0" "'void'\0" "'volatile'\0" "'while'\0" "'{'\0" "'|'\0" "'|='\0" 
"'||'\0" "'}'\0" "'~'\0" ;


/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("!", NULL, RDP_T_33 /* ! */, SCAN_P_IGNORE);
  scan_load_keyword("!=", NULL, RDP_T_3361 /* != */, SCAN_P_IGNORE);
  scan_load_keyword("\"", "\\", RDP_T_34 /* " */, SCAN_P_STRING_ESC);
  scan_load_keyword("#", NULL, RDP_T_35 /* # */, SCAN_P_COMMENT_LINE_VISIBLE);
  scan_load_keyword("%", NULL, RDP_T_37 /* % */, SCAN_P_IGNORE);
  scan_load_keyword("%=", NULL, RDP_T_3761 /* %= */, SCAN_P_IGNORE);
  scan_load_keyword("&", NULL, RDP_T_38 /* & */, SCAN_P_IGNORE);
  scan_load_keyword("&&", NULL, RDP_T_3838 /* && */, SCAN_P_IGNORE);
  scan_load_keyword("&=", NULL, RDP_T_3861 /* &= */, SCAN_P_IGNORE);
  scan_load_keyword("\'", "\\", RDP_T_39 /* ' */, SCAN_P_STRING_ESC);
  scan_load_keyword("(", NULL, RDP_T_40 /* ( */, SCAN_P_IGNORE);
  scan_load_keyword(")", NULL, RDP_T_41 /* ) */, SCAN_P_IGNORE);
  scan_load_keyword("*", NULL, RDP_T_42 /* * */, SCAN_P_IGNORE);
  scan_load_keyword("*=", NULL, RDP_T_4261 /* *= */, SCAN_P_IGNORE);
  scan_load_keyword("+", NULL, RDP_T_43 /* + */, SCAN_P_IGNORE);
  scan_load_keyword("++", NULL, RDP_T_4343 /* ++ */, SCAN_P_IGNORE);
  scan_load_keyword("+=", NULL, RDP_T_4361 /* += */, SCAN_P_IGNORE);
  scan_load_keyword(",", NULL, RDP_T_44 /* , */, SCAN_P_IGNORE);
  scan_load_keyword("-", NULL, RDP_T_45 /* - */, SCAN_P_IGNORE);
  scan_load_keyword("--", NULL, RDP_T_4545 /* -- */, SCAN_P_IGNORE);
  scan_load_keyword("-=", NULL, RDP_T_4561 /* -= */, SCAN_P_IGNORE);
  scan_load_keyword("->", NULL, RDP_T_4562 /* -> */, SCAN_P_IGNORE);
  scan_load_keyword(".", NULL, RDP_T_46 /* . */, SCAN_P_IGNORE);
  scan_load_keyword("..", NULL, RDP_T_4646 /* .. */, SCAN_P_IGNORE);
  scan_load_keyword("...", NULL, RDP_T_464646 /* ... */, SCAN_P_IGNORE);
  scan_load_keyword("/", NULL, RDP_T_47 /* / */, SCAN_P_IGNORE);
  scan_load_keyword("/*", "*/", RDP_T_4742 /* / * */, SCAN_P_COMMENT_VISIBLE);
  scan_load_keyword("/=", NULL, RDP_T_4761 /* /= */, SCAN_P_IGNORE);
  scan_load_keyword(":", NULL, RDP_T_58 /* : */, SCAN_P_IGNORE);
  scan_load_keyword(";", NULL, RDP_T_59 /* ; */, SCAN_P_IGNORE);
  scan_load_keyword("<", NULL, RDP_T_60 /* < */, SCAN_P_IGNORE);
  scan_load_keyword("<<", NULL, RDP_T_6060 /* << */, SCAN_P_IGNORE);
  scan_load_keyword("<<=", NULL, RDP_T_606061 /* <<= */, SCAN_P_IGNORE);
  scan_load_keyword("<=", NULL, RDP_T_6061 /* <= */, SCAN_P_IGNORE);
  scan_load_keyword("=", NULL, RDP_T_61 /* = */, SCAN_P_IGNORE);
  scan_load_keyword("==", NULL, RDP_T_6161 /* == */, SCAN_P_IGNORE);
  scan_load_keyword(">", NULL, RDP_T_62 /* > */, SCAN_P_IGNORE);
  scan_load_keyword(">=", NULL, RDP_T_6261 /* >= */, SCAN_P_IGNORE);
  scan_load_keyword(">>", NULL, RDP_T_6262 /* >> */, SCAN_P_IGNORE);
  scan_load_keyword(">>=", NULL, RDP_T_626261 /* >>= */, SCAN_P_IGNORE);
  scan_load_keyword("?", NULL, RDP_T_63 /* ? */, SCAN_P_IGNORE);
  scan_load_keyword("[", NULL, RDP_T_91 /* [ */, SCAN_P_IGNORE);
  scan_load_keyword("\\", NULL, RDP_T_92 /* \ */, SCAN_P_IGNORE);
  scan_load_keyword("]", NULL, RDP_T_93 /* ] */, SCAN_P_IGNORE);
  scan_load_keyword("^", NULL, RDP_T_94 /* ^ */, SCAN_P_IGNORE);
  scan_load_keyword("^=", NULL, RDP_T_9461 /* ^= */, SCAN_P_IGNORE);
  scan_load_keyword("auto", NULL, RDP_T_auto, SCAN_P_IGNORE);
  scan_load_keyword("break", NULL, RDP_T_break, SCAN_P_IGNORE);
  scan_load_keyword("case", NULL, RDP_T_case, SCAN_P_IGNORE);
  scan_load_keyword("char", NULL, RDP_T_char, SCAN_P_IGNORE);
  scan_load_keyword("const", NULL, RDP_T_const, SCAN_P_IGNORE);
  scan_load_keyword("continue", NULL, RDP_T_continue, SCAN_P_IGNORE);
  scan_load_keyword("default", NULL, RDP_T_default, SCAN_P_IGNORE);
  scan_load_keyword("do", NULL, RDP_T_do, SCAN_P_IGNORE);
  scan_load_keyword("double", NULL, RDP_T_double, SCAN_P_IGNORE);
  scan_load_keyword("else", NULL, RDP_T_else, SCAN_P_IGNORE);
  scan_load_keyword("enum", NULL, RDP_T_enum, SCAN_P_IGNORE);
  scan_load_keyword("extern", NULL, RDP_T_extern, SCAN_P_IGNORE);
  scan_load_keyword("float", NULL, RDP_T_float, SCAN_P_IGNORE);
  scan_load_keyword("for", NULL, RDP_T_for, SCAN_P_IGNORE);
  scan_load_keyword("goto", NULL, RDP_T_goto, SCAN_P_IGNORE);
  scan_load_keyword("if", NULL, RDP_T_if, SCAN_P_IGNORE);
  scan_load_keyword("int", NULL, RDP_T_int, SCAN_P_IGNORE);
  scan_load_keyword("long", NULL, RDP_T_long, SCAN_P_IGNORE);
  scan_load_keyword("register", NULL, RDP_T_register, SCAN_P_IGNORE);
  scan_load_keyword("return", NULL, RDP_T_return, SCAN_P_IGNORE);
  scan_load_keyword("short", NULL, RDP_T_short, SCAN_P_IGNORE);
  scan_load_keyword("signed", NULL, RDP_T_signed, SCAN_P_IGNORE);
  scan_load_keyword("sizeof", NULL, RDP_T_sizeof, SCAN_P_IGNORE);
  scan_load_keyword("static", NULL, RDP_T_static, SCAN_P_IGNORE);
  scan_load_keyword("struct", NULL, RDP_T_struct, SCAN_P_IGNORE);
  scan_load_keyword("switch", NULL, RDP_T_switch, SCAN_P_IGNORE);
  scan_load_keyword("typedef", NULL, RDP_T_typedef, SCAN_P_IGNORE);
  scan_load_keyword("union", NULL, RDP_T_union, SCAN_P_IGNORE);
  scan_load_keyword("unsigned", NULL, RDP_T_unsigned, SCAN_P_IGNORE);
  scan_load_keyword("void", NULL, RDP_T_void, SCAN_P_IGNORE);
  scan_load_keyword("volatile", NULL, RDP_T_volatile, SCAN_P_IGNORE);
  scan_load_keyword("while", NULL, RDP_T_while, SCAN_P_IGNORE);
  scan_load_keyword("{", NULL, RDP_T_123 /* { */, SCAN_P_IGNORE);
  scan_load_keyword("|", NULL, RDP_T_124 /* | */, SCAN_P_IGNORE);
  scan_load_keyword("|=", NULL, RDP_T_12461 /* |= */, SCAN_P_IGNORE);
  scan_load_keyword("||", NULL, RDP_T_124124 /* || */, SCAN_P_IGNORE);
  scan_load_keyword("}", NULL, RDP_T_125 /* } */, SCAN_P_IGNORE);
  scan_load_keyword("~", NULL, RDP_T_126 /* ~ */, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ block_close_stop = SET_NULL;
  set_ block_open_stop = SET_NULL;
  set_ character_stop = SET_NULL;
  set_ close_bracket_first = SET_NULL;
  set_ close_bracket_stop = SET_NULL;
  set_ comment_stop = SET_NULL;
  set_ diadic_first = SET_NULL;
  set_ diadic_stop = SET_NULL;
  set_ field_delim_first = SET_NULL;
  set_ field_delim_stop = SET_NULL;
  set_ item_first = SET_NULL;
  set_ item_stop = SET_NULL;
  set_ keyword_first = SET_NULL;
  set_ keyword_stop = SET_NULL;
  set_ keyword_indent_first = SET_NULL;
  set_ keyword_indent_stop = SET_NULL;
  set_ monadic_first = SET_NULL;
  set_ monadic_stop = SET_NULL;
  set_ open_bracket_first = SET_NULL;
  set_ open_bracket_stop = SET_NULL;
  set_ preprocessor_stop = SET_NULL;
  set_ program_first = SET_NULL;
  set_ program_stop = SET_NULL;
  set_ punctuation_first = SET_NULL;
  set_ punctuation_stop = SET_NULL;
  set_ rdp_item_2_first = SET_NULL;
  set_ rdp_item_3_first = SET_NULL;
  set_ rdp_item_4_first = SET_NULL;
  set_ rdp_item_5_first = SET_NULL;
  set_ rdp_program_10_first = SET_NULL;
  set_ rdp_program_11_first = SET_NULL;
  set_ rdp_program_12_first = SET_NULL;
  set_ rdp_program_13_first = SET_NULL;
  set_ rdp_program_14_first = SET_NULL;
  set_ rdp_program_16_first = SET_NULL;
  set_ rdp_program_17_first = SET_NULL;
  set_ rdp_program_18_first = SET_NULL;
  set_ rdp_program_19_first = SET_NULL;
  set_ rdp_program_6_first = SET_NULL;
  set_ rdp_program_7_first = SET_NULL;
  set_ rdp_program_8_first = SET_NULL;
  set_ rdp_program_9_first = SET_NULL;
  set_ string_stop = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&block_close_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&block_open_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&character_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&close_bracket_first, RDP_T_41 /* ) */, RDP_T_93 /* ] */, SET_END);
  set_assign_list(&close_bracket_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&comment_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&diadic_first, RDP_T_3361 /* != */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, 
RDP_T_43 /* + */, RDP_T_4361 /* += */, RDP_T_45 /* - */, RDP_T_4561 /* -= */, 
RDP_T_47 /* / */, RDP_T_4761 /* /= */, RDP_T_60 /* < */, RDP_T_6060 /* << */, 
RDP_T_606061 /* <<= */, RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, 
RDP_T_63 /* ? */, RDP_T_92 /* \ */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, RDP_T_124 /* | */, 
RDP_T_12461 /* |= */, RDP_T_124124 /* || */, SET_END);
  set_assign_list(&diadic_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&field_delim_first, RDP_T_4562 /* -> */, RDP_T_46 /* . */, SET_END);
  set_assign_list(&field_delim_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&item_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, RDP_T_464646 /* ... */, SET_END);
  set_assign_list(&item_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&keyword_first, RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_double, RDP_T_enum, RDP_T_extern, RDP_T_float, RDP_T_goto, 
RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, RDP_T_short, RDP_T_signed, 
RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_typedef, RDP_T_union, RDP_T_unsigned, 
RDP_T_void, RDP_T_volatile, SET_END);
  set_assign_list(&keyword_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&keyword_indent_first, RDP_T_do, RDP_T_else, RDP_T_for, RDP_T_if, RDP_T_switch, RDP_T_while, SET_END);
  set_assign_list(&keyword_indent_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&monadic_first, RDP_T_33 /* ! */, RDP_T_4343 /* ++ */, RDP_T_4545 /* -- */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&monadic_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&open_bracket_first, RDP_T_40 /* ( */, RDP_T_91 /* [ */, SET_END);
  set_assign_list(&open_bracket_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&preprocessor_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&program_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOLN, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, 
RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, 
RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, RDP_T_464646 /* ... */, 
RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, RDP_T_58 /* : */, 
RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&program_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&punctuation_first, RDP_T_44 /* , */, RDP_T_58 /* : */, RDP_T_59 /* ; */, SET_END);
  set_assign_list(&punctuation_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
  set_assign_list(&rdp_item_2_first, SCAN_P_INTEGER, SCAN_P_REAL, SET_END);
  set_assign_list(&rdp_item_3_first, SCAN_P_INTEGER, SCAN_P_REAL, SET_END);
  set_assign_list(&rdp_item_4_first, SCAN_P_INTEGER, SCAN_P_REAL, SET_END);
  set_assign_list(&rdp_item_5_first, SCAN_P_INTEGER, SCAN_P_REAL, SET_END);
  set_assign_list(&rdp_program_10_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, RDP_T_464646 /* ... */, SET_END);
  set_assign_list(&rdp_program_11_first, RDP_T_4562 /* -> */, RDP_T_46 /* . */, SET_END);
  set_assign_list(&rdp_program_12_first, RDP_T_44 /* , */, RDP_T_58 /* : */, RDP_T_59 /* ; */, SET_END);
  set_assign_list(&rdp_program_13_first, RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_double, RDP_T_enum, RDP_T_extern, RDP_T_float, RDP_T_goto, 
RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, RDP_T_short, RDP_T_signed, 
RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_typedef, RDP_T_union, RDP_T_unsigned, 
RDP_T_void, RDP_T_volatile, SET_END);
  set_assign_list(&rdp_program_14_first, RDP_T_do, RDP_T_else, RDP_T_for, RDP_T_if, RDP_T_switch, RDP_T_while, SET_END);
  set_assign_list(&rdp_program_16_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOLN, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, 
RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, 
RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, RDP_T_464646 /* ... */, 
RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, RDP_T_58 /* : */, 
RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_program_17_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOLN, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, 
RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, 
RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, RDP_T_464646 /* ... */, 
RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, RDP_T_58 /* : */, 
RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_program_18_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOLN, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, 
RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, 
RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, RDP_T_464646 /* ... */, 
RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, RDP_T_58 /* : */, 
RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_program_19_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOLN, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, 
RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, 
RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, 
RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, RDP_T_464646 /* ... */, 
RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, RDP_T_58 /* : */, 
RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_program_6_first, RDP_T_33 /* ! */, RDP_T_4343 /* ++ */, RDP_T_4545 /* -- */, RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_program_7_first, RDP_T_3361 /* != */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, 
RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, 
RDP_T_43 /* + */, RDP_T_4361 /* += */, RDP_T_45 /* - */, RDP_T_4561 /* -= */, 
RDP_T_47 /* / */, RDP_T_4761 /* /= */, RDP_T_60 /* < */, RDP_T_6060 /* << */, 
RDP_T_606061 /* <<= */, RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, 
RDP_T_62 /* > */, RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, 
RDP_T_63 /* ? */, RDP_T_92 /* \ */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, RDP_T_124 /* | */, 
RDP_T_12461 /* |= */, RDP_T_124124 /* || */, SET_END);
  set_assign_list(&rdp_program_8_first, RDP_T_40 /* ( */, RDP_T_91 /* [ */, SET_END);
  set_assign_list(&rdp_program_9_first, RDP_T_41 /* ) */, RDP_T_93 /* ] */, SET_END);
  set_assign_list(&string_stop, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, SCAN_P_EOF, SCAN_P_EOLN, RDP_T_33 /* ! */, 
RDP_T_3361 /* != */, RDP_T_34 /* " */, RDP_T_35 /* # */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, 
RDP_T_38 /* & */, RDP_T_3838 /* && */, RDP_T_3861 /* &= */, RDP_T_39 /* ' */, 
RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, RDP_T_4261 /* *= */, RDP_T_43 /* + */, 
RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, RDP_T_44 /* , */, RDP_T_45 /* - */, 
RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, RDP_T_4562 /* -> */, RDP_T_46 /* . */, 
RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4742 /* / * */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_63 /* ? */, 
RDP_T_91 /* [ */, RDP_T_92 /* \ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, 
RDP_T_auto, RDP_T_break, RDP_T_case, RDP_T_char, RDP_T_const, RDP_T_continue, 
RDP_T_default, RDP_T_do, RDP_T_double, RDP_T_else, RDP_T_enum, RDP_T_extern, RDP_T_float, 
RDP_T_for, RDP_T_goto, RDP_T_if, RDP_T_int, RDP_T_long, RDP_T_register, RDP_T_return, 
RDP_T_short, RDP_T_signed, RDP_T_sizeof, RDP_T_static, RDP_T_struct, RDP_T_switch, 
RDP_T_typedef, RDP_T_union, RDP_T_unsigned, RDP_T_void, RDP_T_volatile, RDP_T_while, 
RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_12461 /* |= */, RDP_T_124124 /* || */, 
RDP_T_125 /* } */, RDP_T_126 /* ~ */,SET_END);
}

/* Parser forward declarations and macros */
static char* block_close(void);
static char* block_open(void);
static char* character(void);
static char* close_bracket(void);
static char* comment(void);
static char* diadic(void);
static char* field_delim(void);
static char* item(void);
static char* keyword(void);
static char* keyword_indent(void);
static char* monadic(void);
static char* open_bracket(void);
static char* preprocessor(void);
void program(void);
static char* punctuation(void);
static char* string(void);

/* Parser functions */
static char* block_close(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_125 /* } */, &block_close_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &block_close_stop, &block_close_stop);
   }
  return result;
}

static char* block_open(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_123 /* { */, &block_open_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &block_open_stop, &block_open_stop);
   }
  return result;
}

static char* character(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_39 /* ' */, &character_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &character_stop, &character_stop);
   }
  return result;
}

static char* close_bracket(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_41 /* ) */, NULL))
    {
      scan_test(NULL, RDP_T_41 /* ) */, &close_bracket_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_93 /* ] */, NULL))
    {
      scan_test(NULL, RDP_T_93 /* ] */, &close_bracket_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &close_bracket_first, &close_bracket_stop)    ;
    scan_test_set(NULL, &close_bracket_stop, &close_bracket_stop);
   }
  return result;
}

static char* comment(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_4742 /* / * */, &comment_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &comment_stop, &comment_stop);
   }
  return result;
}

static char* diadic(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_3838 /* && */, NULL))
    {
      scan_test(NULL, RDP_T_3838 /* && */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_38 /* & */, NULL))
    {
      scan_test(NULL, RDP_T_38 /* & */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_94 /* ^ */, NULL))
    {
      scan_test(NULL, RDP_T_94 /* ^ */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_124 /* | */, NULL))
    {
      scan_test(NULL, RDP_T_124 /* | */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_124124 /* || */, NULL))
    {
      scan_test(NULL, RDP_T_124124 /* || */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_37 /* % */, NULL))
    {
      scan_test(NULL, RDP_T_37 /* % */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_42 /* * */, NULL))
    {
      scan_test(NULL, RDP_T_42 /* * */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_47 /* / */, NULL))
    {
      scan_test(NULL, RDP_T_47 /* / */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_43 /* + */, NULL))
    {
      scan_test(NULL, RDP_T_43 /* + */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_45 /* - */, NULL))
    {
      scan_test(NULL, RDP_T_45 /* - */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_6060 /* << */, NULL))
    {
      scan_test(NULL, RDP_T_6060 /* << */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_6262 /* >> */, NULL))
    {
      scan_test(NULL, RDP_T_6262 /* >> */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_60 /* < */, NULL))
    {
      scan_test(NULL, RDP_T_60 /* < */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_6061 /* <= */, NULL))
    {
      scan_test(NULL, RDP_T_6061 /* <= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_6161 /* == */, NULL))
    {
      scan_test(NULL, RDP_T_6161 /* == */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_62 /* > */, NULL))
    {
      scan_test(NULL, RDP_T_62 /* > */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_6261 /* >= */, NULL))
    {
      scan_test(NULL, RDP_T_6261 /* >= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_63 /* ? */, NULL))
    {
      scan_test(NULL, RDP_T_63 /* ? */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_3361 /* != */, NULL))
    {
      scan_test(NULL, RDP_T_3361 /* != */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_3761 /* %= */, NULL))
    {
      scan_test(NULL, RDP_T_3761 /* %= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_3861 /* &= */, NULL))
    {
      scan_test(NULL, RDP_T_3861 /* &= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_4261 /* *= */, NULL))
    {
      scan_test(NULL, RDP_T_4261 /* *= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_4361 /* += */, NULL))
    {
      scan_test(NULL, RDP_T_4361 /* += */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_4561 /* -= */, NULL))
    {
      scan_test(NULL, RDP_T_4561 /* -= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_4761 /* /= */, NULL))
    {
      scan_test(NULL, RDP_T_4761 /* /= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_61 /* = */, NULL))
    {
      scan_test(NULL, RDP_T_61 /* = */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_9461 /* ^= */, NULL))
    {
      scan_test(NULL, RDP_T_9461 /* ^= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_12461 /* |= */, NULL))
    {
      scan_test(NULL, RDP_T_12461 /* |= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_606061 /* <<= */, NULL))
    {
      scan_test(NULL, RDP_T_606061 /* <<= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_626261 /* >>= */, NULL))
    {
      scan_test(NULL, RDP_T_626261 /* >>= */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_92 /* \ */, NULL))
    {
      scan_test(NULL, RDP_T_92 /* \ */, &diadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &diadic_first, &diadic_stop)    ;
    scan_test_set(NULL, &diadic_stop, &diadic_stop);
   }
  return result;
}

static char* field_delim(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_4562 /* -> */, NULL))
    {
      scan_test(NULL, RDP_T_4562 /* -> */, &field_delim_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_46 /* . */, NULL))
    {
      scan_test(NULL, RDP_T_46 /* . */, &field_delim_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &field_delim_first, &field_delim_stop)    ;
    scan_test_set(NULL, &field_delim_stop, &field_delim_stop);
   }
  return result;
}

static char* item(void)
{
  char* result;
  {
    if (scan_test_set(NULL, &rdp_item_5_first, NULL))
    {
      { /* Start of rdp_item_4 */
        while (1)
        {
          scan_test_set(NULL, &rdp_item_4_first, &item_stop);
          {
             result = SCAN_CAST->id; 
            { /* Start of rdp_item_2 */
              while (1)
              {
                scan_test_set(NULL, &rdp_item_2_first, &item_stop);
                {
                  if (scan_test(NULL, SCAN_P_INTEGER, NULL))
                  {
                    scan_test(NULL, SCAN_P_INTEGER, &item_stop);
                    scan_();
                  }
                  else
                  if (scan_test(NULL, SCAN_P_REAL, NULL))
                  {
                    scan_test(NULL, SCAN_P_REAL, &item_stop);
                    scan_();
                  }
                  else
                    scan_test_set(NULL, &rdp_item_2_first, &item_stop)                  ;
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_item_2 */
            }
          break;   /* hi limit is 1! */
        }
      } /* end of rdp_item_4 */
    }
    else
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
      scan_test(NULL, SCAN_P_ID, &item_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_464646 /* ... */, NULL))
    {
      scan_test(NULL, RDP_T_464646 /* ... */, &item_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &item_first, &item_stop)    ;
    scan_test_set(NULL, &item_stop, &item_stop);
   }
  return result;
}

static char* keyword(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_auto, NULL))
    {
      scan_test(NULL, RDP_T_auto, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_break, NULL))
    {
      scan_test(NULL, RDP_T_break, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_case, NULL))
    {
      scan_test(NULL, RDP_T_case, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_char, NULL))
    {
      scan_test(NULL, RDP_T_char, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_const, NULL))
    {
      scan_test(NULL, RDP_T_const, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_continue, NULL))
    {
      scan_test(NULL, RDP_T_continue, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_default, NULL))
    {
      scan_test(NULL, RDP_T_default, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_double, NULL))
    {
      scan_test(NULL, RDP_T_double, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_enum, NULL))
    {
      scan_test(NULL, RDP_T_enum, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_extern, NULL))
    {
      scan_test(NULL, RDP_T_extern, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_float, NULL))
    {
      scan_test(NULL, RDP_T_float, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_goto, NULL))
    {
      scan_test(NULL, RDP_T_goto, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_int, NULL))
    {
      scan_test(NULL, RDP_T_int, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_long, NULL))
    {
      scan_test(NULL, RDP_T_long, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_register, NULL))
    {
      scan_test(NULL, RDP_T_register, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_return, NULL))
    {
      scan_test(NULL, RDP_T_return, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_short, NULL))
    {
      scan_test(NULL, RDP_T_short, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_signed, NULL))
    {
      scan_test(NULL, RDP_T_signed, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_sizeof, NULL))
    {
      scan_test(NULL, RDP_T_sizeof, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_static, NULL))
    {
      scan_test(NULL, RDP_T_static, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_struct, NULL))
    {
      scan_test(NULL, RDP_T_struct, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_typedef, NULL))
    {
      scan_test(NULL, RDP_T_typedef, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_union, NULL))
    {
      scan_test(NULL, RDP_T_union, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_unsigned, NULL))
    {
      scan_test(NULL, RDP_T_unsigned, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_void, NULL))
    {
      scan_test(NULL, RDP_T_void, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_volatile, NULL))
    {
      scan_test(NULL, RDP_T_volatile, &keyword_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &keyword_first, &keyword_stop)    ;
    scan_test_set(NULL, &keyword_stop, &keyword_stop);
   }
  return result;
}

static char* keyword_indent(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_do, NULL))
    {
      scan_test(NULL, RDP_T_do, &keyword_indent_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_else, NULL))
    {
      scan_test(NULL, RDP_T_else, &keyword_indent_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_for, NULL))
    {
      scan_test(NULL, RDP_T_for, &keyword_indent_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_if, NULL))
    {
      scan_test(NULL, RDP_T_if, &keyword_indent_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_switch, NULL))
    {
      scan_test(NULL, RDP_T_switch, &keyword_indent_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_while, NULL))
    {
      scan_test(NULL, RDP_T_while, &keyword_indent_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &keyword_indent_first, &keyword_indent_stop)    ;
    scan_test_set(NULL, &keyword_indent_stop, &keyword_indent_stop);
   }
  return result;
}

static char* monadic(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_33 /* ! */, NULL))
    {
      scan_test(NULL, RDP_T_33 /* ! */, &monadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_4343 /* ++ */, NULL))
    {
      scan_test(NULL, RDP_T_4343 /* ++ */, &monadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_4545 /* -- */, NULL))
    {
      scan_test(NULL, RDP_T_4545 /* -- */, &monadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_126 /* ~ */, NULL))
    {
      scan_test(NULL, RDP_T_126 /* ~ */, &monadic_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &monadic_first, &monadic_stop)    ;
    scan_test_set(NULL, &monadic_stop, &monadic_stop);
   }
  return result;
}

static char* open_bracket(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_40 /* ( */, NULL))
    {
      scan_test(NULL, RDP_T_40 /* ( */, &open_bracket_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_91 /* [ */, NULL))
    {
      scan_test(NULL, RDP_T_91 /* [ */, &open_bracket_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &open_bracket_first, &open_bracket_stop)    ;
    scan_test_set(NULL, &open_bracket_stop, &open_bracket_stop);
   }
  return result;
}

static char* preprocessor(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_35 /* # */, &preprocessor_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &preprocessor_stop, &preprocessor_stop);
   }
  return result;
}

void program(void)
{
  char* lexeme;
  {
     enum kinds kind;\
               long unsigned line, column;\
               pretty_open(rdp_sourcefilename, rdp_outputfilename);\
            
    if (scan_test_set(NULL, &rdp_program_18_first, NULL))
    { /* Start of rdp_program_18 */
      while (1)
      {
        {
           line = scan_line_number(); column = scan_column_number(); 
          { /* Start of rdp_program_16 */
            while (1)
            {
              scan_test_set(NULL, &rdp_program_16_first, &program_stop);
              {
                if (scan_test(NULL, RDP_T_4742 /* / * */, NULL))
                {
                  lexeme = comment();
                   kind = K_COMMENT;        
                }
                else
                if (scan_test(NULL, RDP_T_34 /* " */, NULL))
                {
                  lexeme = string();
                   kind = K_STRING;         
                }
                else
                if (scan_test(NULL, RDP_T_39 /* ' */, NULL))
                {
                  lexeme = character();
                   kind = K_CHARACTER;      
                }
                else
                if (scan_test(NULL, RDP_T_123 /* { */, NULL))
                {
                  lexeme = block_open();
                   kind = K_BLOCK_OPEN;     
                }
                else
                if (scan_test(NULL, RDP_T_125 /* } */, NULL))
                {
                  lexeme = block_close();
                   kind = K_BLOCK_CLOSE;    
                }
                else
                if (scan_test(NULL, RDP_T_35 /* # */, NULL))
                {
                  lexeme = preprocessor();
                   kind = K_PREPROCESSOR;   
                }
                else
                if (scan_test_set(NULL, &rdp_program_6_first, NULL))
                {
                  lexeme = monadic();
                   kind = K_MONADIC;        
                }
                else
                if (scan_test_set(NULL, &rdp_program_7_first, NULL))
                {
                  lexeme = diadic();
                   kind = K_DIADIC;         
                }
                else
                if (scan_test_set(NULL, &rdp_program_8_first, NULL))
                {
                  lexeme = open_bracket();
                   kind = K_OPEN_BRACKET;   
                }
                else
                if (scan_test_set(NULL, &rdp_program_9_first, NULL))
                {
                  lexeme = close_bracket();
                   kind = K_CLOSE_BRACKET;  
                }
                else
                if (scan_test_set(NULL, &rdp_program_10_first, NULL))
                {
                  lexeme = item();
                   kind = K_ITEM;           
                }
                else
                if (scan_test_set(NULL, &rdp_program_11_first, NULL))
                {
                  lexeme = field_delim();
                   kind = K_FIELD_DELIM;    
                }
                else
                if (scan_test_set(NULL, &rdp_program_12_first, NULL))
                {
                  lexeme = punctuation();
                   kind = K_PUNCTUATION;    
                }
                else
                if (scan_test_set(NULL, &rdp_program_13_first, NULL))
                {
                  lexeme = keyword();
                   kind = K_KEYWORD;        
                }
                else
                if (scan_test_set(NULL, &rdp_program_14_first, NULL))
                {
                  lexeme = keyword_indent();
                   kind = K_KEYWORD_INDENT; 
                }
                else
                if (scan_test(NULL, SCAN_P_EOLN, NULL))
                {
                  scan_test(NULL, SCAN_P_EOLN, &program_stop);
                  lexeme = SCAN_CAST->id;
                  scan_();
                   kind = K_EOLN;           
                }
                else
                  scan_test_set(NULL, &rdp_program_16_first, &program_stop)                ;
                }
              break;   /* hi limit is 1! */
            }
          } /* end of rdp_program_16 */
           pretty_print(lexeme, kind, column, line); 
          }
        if (!scan_test_set(NULL, &rdp_program_18_first, NULL)) break;
      }
    } /* end of rdp_program_18 */
     pretty_close(rdp_sourcefilename, rdp_outputfilename); 
    scan_test_set(NULL, &program_stop, &program_stop);
   }
}

static char* punctuation(void)
{
  char* result;
  {
    if (scan_test(NULL, RDP_T_58 /* : */, NULL))
    {
      scan_test(NULL, RDP_T_58 /* : */, &punctuation_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_59 /* ; */, NULL))
    {
      scan_test(NULL, RDP_T_59 /* ; */, &punctuation_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_44 /* , */, NULL))
    {
      scan_test(NULL, RDP_T_44 /* , */, &punctuation_stop);
      result = SCAN_CAST->id;
      scan_();
    }
    else
      scan_test_set(NULL, &punctuation_first, &punctuation_stop)    ;
    scan_test_set(NULL, &punctuation_stop, &punctuation_stop);
   }
  return result;
}

static char* string(void)
{
  char* result;
  {
    scan_test(NULL, RDP_T_34 /* " */, &string_stop);
    result = SCAN_CAST->id;
    scan_();
    scan_test_set(NULL, &string_stop, &string_stop);
   }
  return result;
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0,            /* make listing flag */

    rdp_lexicalise = 0;            /* print lexicalised output flag */

  unsigned long rdp_textsize = 100000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  arg_message("C pretty printer V1.50 (c) Adrian Johnstone 1997\n" RDP_STAMP "\n\n""Usage: pretty_c [options] source[.c]");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_boolean('L', "Print lexicalised source file", &rdp_lexicalise);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);
  arg_numeric('i', "Number of spaces per indent level: 0 means use tabs (default 2)", &indent_size);
  arg_numeric('c', "Preferred start column for trailing comments (default 30)", &comment_start);

  rdp_sourcefilenames = arg_process(argc, argv);

  /* Fix up filetypes */
  for (rdp_sourcefilenumber = 0; rdp_sourcefilenames[rdp_sourcefilenumber] != NULL; rdp_sourcefilenumber++)
    rdp_sourcefilenames[rdp_sourcefilenumber] = text_default_filetype(rdp_sourcefilenames[rdp_sourcefilenumber], "c");

  if (rdp_filter)
  {
    rdp_sourcefilenames[0] = "-";
    rdp_outputfilename = "-";
    rdp_sourcefilenames[1] = NULL;     /* make sure no further filenames are taken from the array */

  }
  if ((rdp_sourcefilename = rdp_sourcefilenames[0]) == NULL)
     arg_help("no source files specified");

  if (rdp_sourcefilenames[1] != NULL)
    text_message(TEXT_FATAL, "multiple source files not allowed\n");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 1, 0, rdp_symbol_echo, rdp_tokens);
  if (rdp_lexicalise)
    scan_lexicalise();
  rdp_set_initialise();
  rdp_load_keywords();
  if (rdp_verbose)
     text_printf("\nC pretty printer V1.50 (c) Adrian Johnstone 1997\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));

    for (rdp_sourcefilenumber = 0; (rdp_sourcefilename = rdp_sourcefilenames[rdp_sourcefilenumber]) != NULL; rdp_sourcefilenumber++)
    {
      if (text_open(rdp_sourcefilename) == NULL)
        arg_help("unable to open source file");

      text_get_char();
      scan_();

      program();            /* call parser at top level */
      if (text_total_errors() != 0)
        text_message(TEXT_FATAL, "error%s detected in source file ''\n", text_total_errors() == 1 ? "" : "s", rdp_sourcefilename);   /* crash quietly */ 
    }
  }

  rdp_sourcefilename = rdp_sourcefilenames[0];     /* Reset filename to first file in the list */

  if (rdp_symbol_statistics)
  {
    symbol_print_all_table_statistics(11);
    symbol_print_all_table();

  }
  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of pretty_c.c */
